using System.Collections.Frozen;
using System.Collections.Generic;
using Ecliptix.Utilities;

namespace Ecliptix.Core.Services.Core.Localization;

public static class LocalizationData
{
    public static readonly FrozenDictionary<string, string> EnglishStrings = new Dictionary<string, string>
    {
        [ErrorI18NKeys.VALIDATION] = "VALIDATION failed; please review the fields and try again.",
        [ErrorI18NKeys.MAX_ATTEMPTS] = "Maximum attempts reached. Please wait or contact support.",
        [ErrorI18NKeys.INVALID_MOBILE] = "Invalid mobile number format.",
        [ErrorI18NKeys.OTP_EXPIRED] = "Verification code expired. Request a new one.",
        [ErrorI18NKeys.NOT_FOUND] = "Requested resource not found.",
        [ErrorI18NKeys.ALREADY_EXISTS] = "Resource already exists.",
        [ErrorI18NKeys.UNAUTHENTICATED] = "Authentication required. Please sign in again.",
        [ErrorI18NKeys.PERMISSION_DENIED] = "You do not have permission to perform this action.",
        [ErrorI18NKeys.PRECONDITION_FAILED] = "Action cannot be completed in the current state.",
        [ErrorI18NKeys.CONFLICT] = "Operation conflicted with existing data. Refresh and retry.",
        [ErrorI18NKeys.RESOURCE_EXHAUSTED] = "Too many attempts. Please try again later.",
        [ErrorI18NKeys.SERVICE_UNAVAILABLE] = "Service temporarily unavailable. Try again shortly.",
        [ErrorI18NKeys.DEPENDENCY_UNAVAILABLE] = "Upstream dependency is unavailable. Please retry.",
        [ErrorI18NKeys.DEADLINE_EXCEEDED] = "Request timed out. Please try again.",
        [ErrorI18NKeys.CANCELLED] = "Request was cancelled.",
        [ErrorI18NKeys.INTERNAL] = "Something went wrong. Please try again later.",
        [ErrorI18NKeys.DATABASE_UNAVAILABLE] = "Database is unavailable. Please retry later.",

        ["Authentication.ERROR.NavigationFailure"] = "Failed to navigate to main window",
        ["Authentication.ERROR.MembershipIdentifierRequired"] = "Membership identifier is required",
        ["Authentication.ERROR.SESSION_EXPIRED"] = "Your session has expired. Please start the registration process again.",
        ["Authentication.ERROR.RegistrationIncomplete"] = "Registration data is incomplete. Please restart the registration process.",

        ["error.server_unavailable"] = "Server is currently unavailable. Please try again later.",
        ["Authentication.SignUp.MobileVerification.Title"] = "Create Account",
        ["Authentication.SignUp.MobileVerification.Description"] = "Confirm your number. We'll text you a verification code.",
        ["Authentication.SignUp.MobileVerification.Hint"] = "Include country code",
        ["Authentication.SignUp.MobileVerification.Watermark"] = "Mobile Number",
        ["Authentication.SignUp.MobileVerification.Button"] = "Continue",

        ["Authentication.SecureKeyRecovery.MobileVerification.Title"] = "Reset Secure Key",
        ["Authentication.SecureKeyRecovery.MobileVerification.Description"] = "Enter your mobile number to receive a verification code.",
        ["Authentication.SecureKeyRecovery.MobileVerification.Hint"] = "Include country code",
        ["Authentication.SecureKeyRecovery.MobileVerification.Watermark"] = "Mobile Number",
        ["Authentication.SecureKeyRecovery.MobileVerification.Button"] = "Continue",

        ["Authentication.SignUp.VerificationCodeEntry.Title"] = "Verify Your Number",
        ["Authentication.SignUp.VerificationCodeEntry.Description"] = "Enter the code sent to your mobile.",
        ["Authentication.SignUp.VerificationCodeEntry.Hint"] = "Verification Code",
        ["Authentication.SignUp.VerificationCodeEntry.Error_InvalidCode"] = "Invalid code. Please try again.",
        ["Authentication.SignUp.VerificationCodeEntry.Button.Verify"] = "Verify",
        ["Authentication.SignUp.VerificationCodeEntry.Button.Resend"] = "Resend Code",

        ["Authentication.SignUp.NicknameInput.Title"] = "Choose a Nickname",
        ["Authentication.SignUp.NicknameInput.Description"] = "This name will be visible to others.",
        ["Authentication.SignUp.NicknameInput.Hint"] = "Your nickname",
        ["Authentication.SignUp.NicknameInput.Watermark"] = "Nickname",
        ["Authentication.SignUp.NicknameInput.Button"] = "Confirm",

        ["Authentication.SignUp.SecureKeyConfirmation.Title"] = "Set Secure Key",
        ["Authentication.SignUp.SecureKeyConfirmation.Description"] = "Use a strong, unique secure key for security.",
        ["Authentication.SignUp.SecureKeyConfirmation.SECURE_KEY_PLACEHOLDER"] = "Secure Key",
        ["Authentication.SignUp.SecureKeyConfirmation.SECURE_KEY_HINT"] = "8 chars, 1 upper and 1 number",
        ["Authentication.SignUp.SecureKeyConfirmation.VERIFY_SECURE_KEY_PLACEHOLDER"] = "Confirm Secure Key",
        ["Authentication.SignUp.SecureKeyConfirmation.VERIFY_SECURE_KEY_HINT"] = "Re-enter the secure key to confirm",
        ["Authentication.SignUp.SecureKeyConfirmation.Error_SecureKeyMismatch"] = "Secure keys do not match.",
        ["Authentication.SignUp.SecureKeyConfirmation.Button"] = "Set Secure Key",

        ["Authentication.SecureKeyRecovery.Reset.Title"] = "Reset Secure Key",
        ["Authentication.SecureKeyRecovery.Reset.Description"] = "Create a new secure key for your account.",
        ["Authentication.SecureKeyRecovery.Reset.NewSecureKeyPlaceholder"] = "New Secure Key",
        ["Authentication.SecureKeyRecovery.Reset.NewSecureKeyHint"] = "8 chars, 1 upper and 1 number",
        ["Authentication.SecureKeyRecovery.Reset.ConfirmSecureKeyPlaceholder"] = "Confirm New Key",
        ["Authentication.SecureKeyRecovery.Reset.ConfirmSecureKeyHint"] = "Re-enter your new secure key",
        ["Authentication.SecureKeyRecovery.Reset.Button"] = "Reset Secure Key",

        ["Authentication.SignUp.PassPhase.Title"] = "Set PIN",
        ["Authentication.SignUp.PassPhase.Description"] = "For quick and secure authentication.",
        ["Authentication.SignUp.PassPhase.Hint"] = "Your PIN",
        ["Authentication.SignUp.PassPhase.Watermark"] = "••••",
        ["Authentication.SignUp.PassPhase.Button"] = "Confirm PIN",

        ["Authentication.SignIn.Title"] = "Sign In",
        ["Authentication.SignIn.Welcome"] = "Welcome back! Let's get you back to your secure, personalized workspace.",
        ["Authentication.SignIn.MobilePlaceholder"] = "Mobile Number",
        ["Authentication.SignIn.MobileHint"] = "Include country code (e.g., +1)",
        ["Authentication.SignIn.SECURE_KEY_PLACEHOLDER"] = "Secure Key",
        ["Authentication.SignIn.SECURE_KEY_HINT"] = "Stored only on this device",
        ["Authentication.SignIn.AccountRecovery"] = "Forgot key?",
        ["Authentication.SignIn.Continue"] = "Continue",

        ["MobileVerification.ERROR.MobileAlreadyRegistered"] = "A problem occurred with your registration. If you already have an account, please try logging in or use the account recovery option.",
        ["mobile_available_for_registration"] = "This mobile number is available for registration.",
        ["mobile_incomplete_registration_continue"] = "Continue your registration with this mobile number.",
        ["mobile_taken_active_account"] = "This mobile number is already registered with an active account. Please sign in instead.",
        ["mobile_taken_inactive_account"] = "This mobile number is registered but inactive. Please use secure key recovery to regain access.",
        ["mobile_data_corruption_contact_support"] = "There's an issue with your account data. Please contact support for assistance.",
        ["mobile_available_on_this_device"] = "This mobile number is available for registration on this device.",

        ["Verification.ERROR.InvalidOtpCode"] = "Invalid verification code",
        ["Registration.ERROR.Failed"] = "Registration failed",
        ["Verification.ERROR.NoSession"] = "Verification session not found",
        ["Verification.ERROR.SESSION_EXPIRED"] = "Verification session has expired",
        ["Verification.ERROR.NoActiveSession"] = "No active verification session",

        ["Verification.ERROR.MaxAttemptsReached"] = "Maximum verification attempts reached",
        ["Verification.ERROR.VerificationFailed"] = "Verification failed",
        ["Verification.ERROR.SessionNotFound"] = "Verification session not found",
        ["Verification.ERROR.GlobalRateLimitExceeded"] = "Too many requests. Please try again later",
        ["Verification.Info.Redirecting"] = "Redirecting...",
        ["Verification.Info.RedirectingInSeconds"] = "Redirecting in {0} seconds...",

        ["ValidationErrors.MobileNumber.MUST_START_WITH_COUNTRY_CODE"] = "Must start with +",
        ["ValidationErrors.MobileNumber.CONTAINS_NON_DIGITS"] = "Digits only after code",
        ["ValidationErrors.MobileNumber.INCORRECT_LENGTH"] = "{0}-{1} digits required",
        ["ValidationErrors.MobileNumber.CANNOT_BE_EMPTY"] = "REQUIRED",

        ["ResponseErrors.MobileNumber.AccountAlreadyRegistered"] = "Account on this number already registered. Try sign in or use forgot secure key.",
        ["ResponseErrors.MobileNumber.UnexpectedMembershipStatus"] = "Unexpected membership status. Please try again.",
        ["ResponseErrors.Common.TimeoutExceeded"] = "The operation timed out. Please try again.",

        ["ValidationErrors.MobileNumber.REQUIRED"] = "Mobile number is required",
        ["ValidationErrors.MobileNumberIdentifier.REQUIRED"] = "Mobile number identifier is required",
        ["ValidationErrors.DeviceIdentifier.REQUIRED"] = "Device identifier is required",
        ["ValidationErrors.SessionIdentifier.REQUIRED"] = "Session identifier is required",
        ["ValidationErrors.MembershipIdentifier.REQUIRED"] = "Membership identifier is required",

        ["ValidationErrors.SecureKey.REQUIRED"] = "REQUIRED",
        ["ValidationErrors.SecureKey.MIN_LENGTH"] = "Min {0} characters",
        ["ValidationErrors.SecureKey.MAX_LENGTH"] = "Max {0} characters",
        ["ValidationErrors.SecureKey.NO_SPACES"] = "No spaces allowed",
        ["ValidationErrors.SecureKey.NO_UPPERCASE"] = "Requires an uppercase letter",
        ["ValidationErrors.SecureKey.NO_LOWERCASE"] = "Requires a lowercase letter",
        ["ValidationErrors.SecureKey.NO_DIGIT"] = "Requires a digit",
        ["ValidationErrors.SecureKey.TOO_SIMPLE"] = "Try adding more variety",
        ["ValidationErrors.SecureKey.TOO_COMMON"] = "Too common",
        ["ValidationErrors.SecureKey.SEQUENTIAL_PATTERN"] = "No sequences (e.g., abc, 123)",
        ["ValidationErrors.SecureKey.REPEATED_CHARS"] = "No repeats (e.g., aaa, 111)",
        ["ValidationErrors.SecureKey.LACKS_DIVERSITY"] = "Requires {0} character types (A, a, 1, $)",
        ["ValidationErrors.SecureKey.CONTAINS_APP_NAME"] = "Cannot contain app name",
        ["ValidationErrors.SecureKey.InvalidCredentials"] = "Invalid credentials",
        ["ValidationErrors.SecureKey.NON_ENGLISH_LETTERS"] = "Latin letters only",
        ["ValidationErrors.SecureKey.NO_SPECIAL_CHAR"] = "Requires a special character",

        ["ValidationErrors.VerifySecureKey.DoesNotMatch"] = "Secure keys do not match",

        ["ValidationErrors.SecureKeyStrength.Invalid"] = "Invalid",
        ["ValidationErrors.SecureKeyStrength.VeryWeak"] = "Very Weak",
        ["ValidationErrors.SecureKeyStrength.Weak"] = "Weak",
        ["ValidationErrors.SecureKeyStrength.Good"] = "Good",
        ["ValidationErrors.SecureKeyStrength.Strong"] = "Strong",
        ["ValidationErrors.SecureKeyStrength.VeryStrong"] = "Very Strong",

        ["ValidationWarnings.SecureKey.NonLatinLetter"] = "Latin letters only",
        ["ValidationWarnings.SecureKey.InvalidCharacter"] = "Invalid character used",
        ["ValidationWarnings.SecureKey.MultipleCharacters"] = "Multiple instances of character type",

        ["Welcome.SignInButton"] = "Sign In",
        ["Welcome.CreateAccountButton"] = "Create Account",

        ["Footer.PrivacyPolicy"] = "Privacy Policy",
        ["Footer.TermsOfService"] = "Terms of Service",
        ["Footer.Support"] = "Support",
        ["Footer.AgreementText"] = "By continuing, you agree to our Terms and Privacy Policy.",
        ["Footer.Copyright"] = "© 2025 Horizon Dynamics. All rights reserved.",

        ["Navigation.Back"] = "Back",
        ["Navigation.Close"] = "Close",
        ["Navigation.Minimize"] = "Minimize",
        ["Navigation.Maximize"] = "Maximize",

        ["Common.Loading"] = "Loading...",
        ["Common.ERROR"] = "ERROR",
        ["Common.Success"] = "Success",
        ["Common.Cancel"] = "Cancel",
        ["Common.UnexpectedError"] = "An unexpected error occurred",
        ["Common.Ok"] = "OK",
        ["Common.NoInternetConnection"] = "No internet connection",
        ["Common.CheckConnection"] = "Check your internet connection",

        ["NetworkNotification.NoInternet.Title"] = "No Internet Connection",
        ["NetworkNotification.NoInternet.Description"] = "Check your connection and try again",
        ["NetworkNotification.CheckingInternet.Title"] = "Checking Connection",
        ["NetworkNotification.CheckingInternet.Description"] = "Verifying internet connectivity",
        ["NetworkNotification.InternetRestored.Title"] = "Connection Restored",
        ["NetworkNotification.InternetRestored.Description"] = "Internet connection is back",
        ["NetworkNotification.Connecting.Title"] = "Connecting",
        ["NetworkNotification.Connecting.Description"] = "Establishing connection to server",
        ["NetworkNotification.Reconnecting.Title"] = "Reconnecting",
        ["NetworkNotification.Reconnecting.Description"] = "Attempting to reconnect to server",
        ["NetworkNotification.ServerNotResponding.Title"] = "Server Unavailable",
        ["NetworkNotification.ServerNotResponding.Description"] = "Our servers are not responding",
        ["NetworkNotification.ServerShuttingDown.Title"] = "Server Maintenance",
        ["NetworkNotification.ServerShuttingDown.Description"] = "Server is shutting down",
        ["NetworkNotification.RetriesExhausted.Title"] = "Connection Failed",
        ["NetworkNotification.RetriesExhausted.Description"] = "Unable to connect after multiple attempts",
        ["NetworkNotification.ServerReconnected.Title"] = "Reconnected",
        ["NetworkNotification.ServerReconnected.Description"] = "Successfully reconnected to server",
        ["NetworkNotification.Button.Retry"] = "Retry",

        ["LanguageDetection.Title"] = "Language Suggestion",
        ["LanguageDetection.Prompt"] = "Switch to {0}?",
        ["LanguageDetection.Button.Confirm"] = "Switch Language",
        ["LanguageDetection.Button.Decline"] = "Not Now"
    }.ToFrozenDictionary();

    public static readonly FrozenDictionary<string, string> UkrainianStrings = new Dictionary<string, string>
    {
        [ErrorI18NKeys.VALIDATION] = "Перевірка не пройшла; перевірте дані та повторіть спробу.",
        [ErrorI18NKeys.MAX_ATTEMPTS] = "Досягнуто максимальну кількість спроб. Зачекайте або зверніться до підтримки.",
        [ErrorI18NKeys.INVALID_MOBILE] = "Неправильний формат номера телефону.",
        [ErrorI18NKeys.OTP_EXPIRED] = "Термін дії коду підтвердження минув. Запитайте новий.",
        [ErrorI18NKeys.NOT_FOUND] = "Запитаний ресурс не знайдено.",
        [ErrorI18NKeys.ALREADY_EXISTS] = "Такий ресурс уже існує.",
        [ErrorI18NKeys.UNAUTHENTICATED] = "Потрібна автентифікація. Увійдіть ще раз.",
        [ErrorI18NKeys.PERMISSION_DENIED] = "У вас немає дозволу на цю дію.",
        [ErrorI18NKeys.PRECONDITION_FAILED] = "Дію неможливо виконати в поточному стані.",
        [ErrorI18NKeys.CONFLICT] = "Операція конфліктує з наявними даними. Оновіть та повторіть.",
        [ErrorI18NKeys.RESOURCE_EXHAUSTED] = "Забагато спроб. Спробуйте пізніше.",
        [ErrorI18NKeys.SERVICE_UNAVAILABLE] = "Сервіс тимчасово недоступний. Спробуйте пізніше.",
        [ErrorI18NKeys.DEPENDENCY_UNAVAILABLE] = "Зовнішня залежність недоступна. Повторіть спробу.",
        [ErrorI18NKeys.DEADLINE_EXCEEDED] = "Час очікування запиту вичерпано. Спробуйте ще раз.",
        [ErrorI18NKeys.CANCELLED] = "Запит було скасовано.",
        [ErrorI18NKeys.INTERNAL] = "Сталася помилка. Спробуйте пізніше.",
        [ErrorI18NKeys.DATABASE_UNAVAILABLE] = "База даних недоступна. Повторіть спробу пізніше.",
        ["error.server_unavailable"] = "Сервер наразі недоступний. Будь ласка, спробуйте пізніше.",

        ["Authentication.ERROR.NavigationFailure"] = "Не вдалося перейти до головного вікна",
        ["Authentication.ERROR.MembershipIdentifierRequired"] = "Ідентифікатор учасника є обов'язковим",
        ["Authentication.ERROR.SESSION_EXPIRED"] = "Ваша сесія закінчилася. Будь ласка, почніть реєстрацію спочатку.",
        ["Authentication.ERROR.RegistrationIncomplete"] = "Дані реєстрації неповні. Будь ласка, почніть процес реєстрації знову.",

        ["Authentication.SignUp.MobileVerification.Title"] = "Створити акаунт",
        ["Authentication.SignUp.MobileVerification.Description"] = "Підтвердьте номер. Ми надішлемо код в SMS.",
        ["Authentication.SignUp.MobileVerification.Hint"] = "Включно з кодом країни",
        ["Authentication.SignUp.MobileVerification.Watermark"] = "Номер мобільного",
        ["Authentication.SignUp.MobileVerification.Button"] = "Продовжити",

        ["Authentication.SecureKeyRecovery.MobileVerification.Title"] = "Скинути ключ безпеки",
        ["Authentication.SecureKeyRecovery.MobileVerification.Description"] = "Підтвердьте номер для отримання коду підтвердження.",
        ["Authentication.SecureKeyRecovery.MobileVerification.Hint"] = "Включно з кодом країни",
        ["Authentication.SecureKeyRecovery.MobileVerification.Watermark"] = "Номер мобільного",
        ["Authentication.SecureKeyRecovery.MobileVerification.Button"] = "Продовжити",

        ["Authentication.SignUp.VerificationCodeEntry.Title"] = "Підтвердження номера",
        ["Authentication.SignUp.VerificationCodeEntry.Description"] = "Введіть код, надісланий на ваш мобільний.",
        ["Authentication.SignUp.VerificationCodeEntry.Hint"] = "Код підтвердження",
        ["Authentication.SignUp.VerificationCodeEntry.Error_InvalidCode"] = "Неправильний код. Спробуйте ще раз.",
        ["Authentication.SignUp.VerificationCodeEntry.Button.Verify"] = "Підтвердити",
        ["Authentication.SignUp.VerificationCodeEntry.Button.Resend"] = "Надіслати знову",

        ["Authentication.SignUp.NicknameInput.Title"] = "Оберіть нікнейм",
        ["Authentication.SignUp.NicknameInput.Description"] = "Це ім'я буде видимим для інших.",
        ["Authentication.SignUp.NicknameInput.Hint"] = "Ваш нікнейм",
        ["Authentication.SignUp.NicknameInput.Watermark"] = "Нікнейм",
        ["Authentication.SignUp.NicknameInput.Button"] = "Підтвердити",

        ["Authentication.SignUp.SecureKeyConfirmation.Title"] = "Встановіть ключ безпеки",
        ["Authentication.SignUp.SecureKeyConfirmation.Description"] = "Для безпеки використовуйте надійний ключ безпеки.",
        ["Authentication.SignUp.SecureKeyConfirmation.SECURE_KEY_PLACEHOLDER"] = "Ключ безпеки",
        ["Authentication.SignUp.SecureKeyConfirmation.SECURE_KEY_HINT"] = "8 символів, 1 велика літера та 1 цифра",
        ["Authentication.SignUp.SecureKeyConfirmation.VERIFY_SECURE_KEY_PLACEHOLDER"] = "Повторіть ключ",
        ["Authentication.SignUp.SecureKeyConfirmation.VERIFY_SECURE_KEY_HINT"] = "Введіть ключ ще раз для підтвердження",
        ["Authentication.SignUp.SecureKeyConfirmation.Error_SecureKeyMismatch"] = "Ключі безпеки не збігаються.",
        ["Authentication.SignUp.SecureKeyConfirmation.Button"] = "Встановити ключ безпеки",

        ["Authentication.SecureKeyRecovery.Reset.Title"] = "Скидання ключа безпеки",
        ["Authentication.SecureKeyRecovery.Reset.Description"] = "Створіть новий ключ безпеки для облікового запису.",
        ["Authentication.SecureKeyRecovery.Reset.NewSecureKeyPlaceholder"] = "Новий ключ безпеки",
        ["Authentication.SecureKeyRecovery.Reset.NewSecureKeyHint"] = "8 символів, 1 велика літера та 1 цифра",
        ["Authentication.SecureKeyRecovery.Reset.ConfirmSecureKeyPlaceholder"] = "Підтвердіть новий ключ",
        ["Authentication.SecureKeyRecovery.Reset.ConfirmSecureKeyHint"] = "Введіть новий ключ ще раз",
        ["Authentication.SecureKeyRecovery.Reset.Button"] = "Скинути ключ безпеки",

        ["Authentication.SignUp.PassPhase.Title"] = "Встановіть PIN-код",
        ["Authentication.SignUp.PassPhase.Description"] = "Для швидкої та безпечної автентифікації.",
        ["Authentication.SignUp.PassPhase.Hint"] = "Ваш PIN-код",
        ["Authentication.SignUp.PassPhase.Watermark"] = "••••",
        ["Authentication.SignUp.PassPhase.Button"] = "Підтвердити PIN",

        ["Authentication.SignIn.Title"] = "Вхід",
        ["Authentication.SignIn.Welcome"] = "З поверненням! Увійдіть у свій захищений простір.",
        ["Authentication.SignIn.MobilePlaceholder"] = "Номер телефону",
        ["Authentication.SignIn.MobileHint"] = "Почніть з коду країни (напр., +380)",
        ["Authentication.SignIn.SECURE_KEY_PLACEHOLDER"] = "Ключ безпеки",
        ["Authentication.SignIn.SECURE_KEY_HINT"] = "Зберігається лише на цьому пристрої",
        ["Authentication.SignIn.AccountRecovery"] = "Забули ключ?",
        ["Authentication.SignIn.Continue"] = "Продовжити",

        ["MobileVerification.ERROR.MobileAlreadyRegistered"] = "Під час реєстрації сталася помилка. Якщо у вас вже є акаунт, будь ласка, спробуйте увійти або скористайтеся опцією відновлення доступу.",
        ["mobile_available_for_registration"] = "Цей номер доступний для реєстрації.",
        ["mobile_incomplete_registration_continue"] = "Продовжіть реєстрацію з цим номером.",
        ["mobile_taken_active_account"] = "Цей номер вже зареєстровано з активним акаунтом. Будь ласка, увійдіть.",
        ["mobile_taken_inactive_account"] = "Цей номер зареєстровано, але акаунт неактивний. Скористайтеся відновленням ключа безпеки.",
        ["mobile_data_corruption_contact_support"] = "Виникла проблема з даними вашого акаунта. Будь ласка, зверніться до підтримки.",
        ["mobile_available_on_this_device"] = "Цей номер доступний для реєстрації на цьому пристрої.",

        ["Verification.ERROR.InvalidOtpCode"] = "Неправильний код підтвердження",
        ["Registration.ERROR.Failed"] = "Не вдалося зареєструватися",
        ["Verification.ERROR.NoSession"] = "Сесія підтвердження не знайдена",
        ["Verification.ERROR.SESSION_EXPIRED"] = "Термін дії сесії підтвердження минув",
        ["Verification.ERROR.NoActiveSession"] = "Немає активної сесії підтвердження",

        ["Verification.ERROR.MaxAttemptsReached"] = "Досягнуто максимальну кількість спроб підтвердження",
        ["Verification.ERROR.VerificationFailed"] = "Підтвердження не вдалося",
        ["Verification.ERROR.SessionNotFound"] = "Сесія підтвердження не знайдена",
        ["Verification.ERROR.GlobalRateLimitExceeded"] = "Занадто багато запитів. Спробуйте пізніше",
        ["Verification.Info.Redirecting"] = "Перенаправлення...",
        ["Verification.Info.RedirectingInSeconds"] = "Перенаправлення через {0} секунд...",

        ["ValidationErrors.MobileNumber.MUST_START_WITH_COUNTRY_CODE"] = "Має починатись із +",
        ["ValidationErrors.MobileNumber.CONTAINS_NON_DIGITS"] = "Лише цифри після коду",
        ["ValidationErrors.MobileNumber.INCORRECT_LENGTH"] = "Потрібно {0}-{1} цифр",
        ["ValidationErrors.MobileNumber.CANNOT_BE_EMPTY"] = "Обов'язкове поле",

        ["ValidationErrors.MobileNumber.REQUIRED"] = "Номер мобільного телефону є обов'язковим",
        ["ValidationErrors.MobileNumberIdentifier.REQUIRED"] = "Ідентифікатор номера мобільного телефону є обов'язковим",
        ["ValidationErrors.DeviceIdentifier.REQUIRED"] = "Ідентифікатор пристрою є обов'язковим",
        ["ValidationErrors.SessionIdentifier.REQUIRED"] = "Ідентифікатор сесії є обов'язковим",
        ["ValidationErrors.MembershipIdentifier.REQUIRED"] = "Ідентифікатор учасника є обов'язковим",

        ["ResponseErrors.MobileNumber.AccountAlreadyRegistered"] = "Акаунт з цим номером вже зареєстровано. Спробуйте увійти або скористайтеся відновленням пароля.",
        ["ResponseErrors.MobileNumber.UnexpectedMembershipStatus"] = "Неочікуваний статус системи. Спробуйте ще раз.",
        ["ResponseErrors.Common.TimeoutExceeded"] = "Операція перевищила час очікування. Спробуйте ще раз.",

        ["ValidationErrors.SecureKey.REQUIRED"] = "Обов'язкове поле",
        ["ValidationErrors.SecureKey.MIN_LENGTH"] = "Мін. {0} символів",
        ["ValidationErrors.SecureKey.MAX_LENGTH"] = "Макс. {0} символів",
        ["ValidationErrors.SecureKey.NO_SPACES"] = "Без пробілів",
        ["ValidationErrors.SecureKey.NO_UPPERCASE"] = "Потрібна велика літера",
        ["ValidationErrors.SecureKey.NO_LOWERCASE"] = "Потрібна мала літера",
        ["ValidationErrors.SecureKey.NO_DIGIT"] = "Потрібна цифра",
        ["ValidationErrors.SecureKey.TOO_SIMPLE"] = "Додайте більше різноманітності",
        ["ValidationErrors.SecureKey.TOO_COMMON"] = "Занадто поширений",
        ["ValidationErrors.SecureKey.SEQUENTIAL_PATTERN"] = "Без послідовностей (abc, 123)",
        ["ValidationErrors.SecureKey.REPEATED_CHARS"] = "Без повторів (aaa, 111)",
        ["ValidationErrors.SecureKey.LACKS_DIVERSITY"] = "Потрібно {0} типи символів (A, a, 1, $)",
        ["ValidationErrors.SecureKey.CONTAINS_APP_NAME"] = "Не може містити назву додатку",
        ["ValidationErrors.SecureKey.InvalidCredentials"] = "Неправильні облікові дані",
        ["ValidationErrors.SecureKey.NON_ENGLISH_LETTERS"] = "Лише латинські літери",
        ["ValidationErrors.SecureKey.NO_SPECIAL_CHAR"] = "Потрібен спеціальний символ",

        ["ValidationErrors.VerifySecureKey.DoesNotMatch"] = "Ключі безпеки не збігаються",

        ["ValidationErrors.SecureKeyStrength.Invalid"] = "Некоректний",
        ["ValidationErrors.SecureKeyStrength.VeryWeak"] = "Дуже слабкий",
        ["ValidationErrors.SecureKeyStrength.Weak"] = "Слабкий",
        ["ValidationErrors.SecureKeyStrength.Good"] = "Хороший",
        ["ValidationErrors.SecureKeyStrength.Strong"] = "Сильний",
        ["ValidationErrors.SecureKeyStrength.VeryStrong"] = "Дуже сильний",

        ["ValidationWarnings.SecureKey.NonLatinLetter"] = "Лише латинські літери",
        ["ValidationWarnings.SecureKey.InvalidCharacter"] = "Використано недопустимий символ",
        ["ValidationWarnings.SecureKey.MultipleCharacters"] = "Кілька символів одного типу",

        ["Welcome.SignInButton"] = "Увійти",
        ["Welcome.CreateAccountButton"] = "Створити акаунт",

        ["Footer.PrivacyPolicy"] = "Політика конфіденційності",
        ["Footer.TermsOfService"] = "Умови надання послуг",
        ["Footer.Support"] = "Підтримка",
        ["Footer.AgreementText"] = "Продовжуючи, ви погоджуєтесь з нашими Умовами та Політикою конфіденціальності.",
        ["Footer.Copyright"] = "© 2025 Horizon Dynamics. Усі права захищено.",

        ["Navigation.Back"] = "Назад",
        ["Navigation.Close"] = "Закрити",
        ["Navigation.Minimize"] = "Згорнути",
        ["Navigation.Maximize"] = "Розгорнути",

        ["Common.Loading"] = "Завантаження...",
        ["Common.ERROR"] = "Помилка",
        ["Common.Success"] = "Успішно",
        ["Common.Cancel"] = "Скасувати",
        ["Common.UnexpectedError"] = "Несподівана помилка",
        ["Common.Ok"] = "Гаразд",
        ["Common.NoInternetConnection"] = "Немає підключення до інтернету",
        ["Common.CheckConnection"] = "Перевірте ваше інтернет-з'єднання",

        ["NetworkNotification.NoInternet.Title"] = "Немає підключення до інтернету",
        ["NetworkNotification.NoInternet.Description"] = "Перевірте з'єднання та спробуйте знову",
        ["NetworkNotification.CheckingInternet.Title"] = "Перевірка з'єднання",
        ["NetworkNotification.CheckingInternet.Description"] = "Перевіряємо підключення до інтернету",
        ["NetworkNotification.InternetRestored.Title"] = "З'єднання відновлено",
        ["NetworkNotification.InternetRestored.Description"] = "Підключення до інтернету відновлено",
        ["NetworkNotification.Connecting.Title"] = "Підключення",
        ["NetworkNotification.Connecting.Description"] = "Встановлюємо з'єднання з сервером",
        ["NetworkNotification.Reconnecting.Title"] = "Перепідключення",
        ["NetworkNotification.Reconnecting.Description"] = "Намагаємось відновити з'єднання з сервером",
        ["NetworkNotification.ServerNotResponding.Title"] = "Сервер недоступний",
        ["NetworkNotification.ServerNotResponding.Description"] = "Наші сервери не відповідають",
        ["NetworkNotification.ServerShuttingDown.Title"] = "Обслуговування сервера",
        ["NetworkNotification.ServerShuttingDown.Description"] = "Сервер вимикається",
        ["NetworkNotification.RetriesExhausted.Title"] = "Не вдалось підключитись",
        ["NetworkNotification.RetriesExhausted.Description"] = "Неможливо підключитись після кількох спроб",
        ["NetworkNotification.ServerReconnected.Title"] = "Підключено",
        ["NetworkNotification.ServerReconnected.Description"] = "Успішно підключено до сервера",
        ["NetworkNotification.Button.Retry"] = "Повторити",

        ["LanguageDetection.Title"] = "Пропозиція мови",
        ["LanguageDetection.Prompt"] = "Перемкнутись на {0}?",
        ["LanguageDetection.Button.Confirm"] = "Змінити мову",
        ["LanguageDetection.Button.Decline"] = "Не зараз"
    }.ToFrozenDictionary();

    public static readonly FrozenDictionary<string, FrozenDictionary<string, string>> AllLanguages = new Dictionary<string, FrozenDictionary<string, string>>
    {
        ["en-US"] = EnglishStrings,
        ["uk-UA"] = UkrainianStrings
    }.ToFrozenDictionary();
}
