using System.Collections.Frozen;
using System.Collections.Generic;
using Ecliptix.Utilities;

namespace Ecliptix.Core.Shell.Services.Localization;

public static class LocalizationData
{
    public static readonly FrozenDictionary<string, string> EnglishStrings = new Dictionary<string, string>
    {
        [ErrorI18NKeys.VALIDATION] = "VALIDATION failed; please review the fields and try again.",
        [ErrorI18NKeys.MAX_ATTEMPTS] = "Maximum attempts reached. Please wait or contact support.",
        [ErrorI18NKeys.INVALID_MOBILE] = "Invalid mobile number format.",
        [ErrorI18NKeys.OTP_EXPIRED] = "Verification code expired. Request a new one.",
        [ErrorI18NKeys.NOT_FOUND] = "Requested resource not found.",
        [ErrorI18NKeys.ALREADY_EXISTS] = "Resource already exists.",
        [ErrorI18NKeys.UNAUTHENTICATED] = "Authentication required. Please sign in again.",
        [ErrorI18NKeys.PERMISSION_DENIED] = "You do not have permission to perform this action.",
        [ErrorI18NKeys.PRECONDITION_FAILED] = "Action cannot be completed in the current state.",
        [ErrorI18NKeys.CONFLICT] = "Operation conflicted with existing data. Refresh and retry.",
        [ErrorI18NKeys.RESOURCE_EXHAUSTED] = "Too many attempts. Please try again later.",
        [ErrorI18NKeys.SERVICE_UNAVAILABLE] = "Service temporarily unavailable. Try again shortly.",
        [ErrorI18NKeys.DEPENDENCY_UNAVAILABLE] = "Upstream dependency is unavailable. Please retry.",
        [ErrorI18NKeys.DEADLINE_EXCEEDED] = "Request timed out. Please try again.",
        [ErrorI18NKeys.CANCELLED] = "Request was cancelled.",
        [ErrorI18NKeys.INTERNAL] = "Something went wrong. Please try again later.",
        [ErrorI18NKeys.DATABASE_UNAVAILABLE] = "Database is unavailable. Please retry later.",
        [LocalizationKeys.Authentication.Error.NAVIGATION_FAILURE] = "Failed to navigate to main window",
        [LocalizationKeys.Authentication.Error.MEMBERSHIP_IDENTIFIER_REQUIRED] =
            "Membership identifier is required",
        [LocalizationKeys.Authentication.Error.SESSION_EXPIRED] =
            "Your session has expired. Please start the registration process again.",
        [LocalizationKeys.Authentication.Error.REGISTRATION_INCOMPLETE] =
            "Registration data is incomplete. Please restart the registration process.",
        [LocalizationKeys.Common.SERVER_UNAVAILABLE] = "Server is currently unavailable. Please try again later.",
        [LocalizationKeys.Authentication.SignUp.SignUpMobileVerification.TITLE] = "Create Account",
        [LocalizationKeys.Authentication.SignUp.SignUpMobileVerification.DESCRIPTION] =
            "Let's start by verifying your mobile number. We'll send you a secure verification code.",
        [LocalizationKeys.Authentication.SignUp.SignUpMobileVerification.HINT] = "Please ensure the number is correct",
        [LocalizationKeys.Authentication.SignUp.SignUpMobileVerification.WATERMARK] = "Mobile Number",
        [LocalizationKeys.Authentication.SignUp.SignUpMobileVerification.BUTTON] = "Continue",
        [LocalizationKeys.Authentication.SecureKeyRecovery.RecoveryMobileVerification.TITLE] = "Reset Secure Key",
        [LocalizationKeys.Authentication.SecureKeyRecovery.RecoveryMobileVerification.DESCRIPTION] =
            "Enter your mobile number to receive a verification code.",
        [LocalizationKeys.Authentication.SecureKeyRecovery.RecoveryMobileVerification.HINT] = "Please ensure the number is correct",
        [LocalizationKeys.Authentication.SecureKeyRecovery.RecoveryMobileVerification.WATERMARK] = "Mobile Number",
        [LocalizationKeys.Authentication.SecureKeyRecovery.RecoveryMobileVerification.BUTTON] = "Continue",
        [LocalizationKeys.Authentication.SignUp.VerificationCodeEntry.TITLE] = "Verify Your Number",
        [LocalizationKeys.Authentication.SignUp.VerificationCodeEntry.DESCRIPTION] =
            "We sent a 6-digit code to {0}. Enter it below to verify your number.",
        [LocalizationKeys.Authentication.SignUp.VerificationCodeEntry.HINT] = "Verification Code",
        [LocalizationKeys.Authentication.SignUp.VerificationCodeEntry.ERROR_INVALID_CODE] =
            "Invalid code. Please try again.",
        [LocalizationKeys.Authentication.SignUp.VerificationCodeEntry.BUTTON_VERIFY] = "Verify",
        [LocalizationKeys.Authentication.SignUp.VerificationCodeEntry.BUTTON_RESEND] = "Resend",
        [LocalizationKeys.Authentication.SignUp.VerificationCodeEntry.NOT_RECEIVED] = "Didn't receive a code?",
        [LocalizationKeys.Authentication.SignUp.NicknameInput.TITLE] = "Choose a Nickname",
        [LocalizationKeys.Authentication.SignUp.NicknameInput.DESCRIPTION] = "This name will be visible to others.",
        [LocalizationKeys.Authentication.SignUp.NicknameInput.HINT] = "Your nickname",
        [LocalizationKeys.Authentication.SignUp.NicknameInput.WATERMARK] = "Nickname",
        [LocalizationKeys.Authentication.SignUp.NicknameInput.BUTTON] = "Confirm",
        [LocalizationKeys.Authentication.SignUp.SecureKeyConfirmation.TITLE] = "Set Secure Key",
        [LocalizationKeys.Authentication.SignUp.SecureKeyConfirmation.DESCRIPTION] =
            "Choose a strong secure key. This will be used to access your account and is stored only on your device.",
        [LocalizationKeys.Authentication.SignUp.SecureKeyConfirmation.SECURE_KEY_PLACEHOLDER] = "Secure Key",
        [LocalizationKeys.Authentication.SignUp.SecureKeyConfirmation.SECURE_KEY_HINT] =
            "Min 6 chars: uppercase, lowercase, number",
        [LocalizationKeys.Authentication.SignUp.SecureKeyConfirmation.VERIFY_SECURE_KEY_PLACEHOLDER] =
            "Confirm Secure Key",
        [LocalizationKeys.Authentication.SignUp.SecureKeyConfirmation.VERIFY_SECURE_KEY_HINT] =
            "Re-enter the secure key to confirm",
        [LocalizationKeys.Authentication.SignUp.SecureKeyConfirmation.ERROR_SECURE_KEY_MISMATCH] =
            "Secure keys do not match.",
        [LocalizationKeys.Authentication.SignUp.SecureKeyConfirmation.BUTTON] = "Continue",
        [LocalizationKeys.Authentication.SignUp.SecureKeyConfirmation.REQUIREMENTS_SUCCESS_TITLE] = "All minimum requirements are met",
        [LocalizationKeys.Authentication.SignUp.SecureKeyConfirmation.REQUIREMENTS_TITLE] = "Security Requirements:",
        [LocalizationKeys.Authentication.SecureKeyRecovery.Reset.TITLE] = "Reset Secure Key",
        [LocalizationKeys.Authentication.SecureKeyRecovery.Reset.DESCRIPTION] =
            "Create a new secure key for your account.",
        [LocalizationKeys.Authentication.SecureKeyRecovery.Reset.NEW_SECURE_KEY_PLACEHOLDER] = "New Secure Key",
        [LocalizationKeys.Authentication.SecureKeyRecovery.Reset.NEW_SECURE_KEY_HINT] =
            "Min 6 chars: uppercase, lowercase, number",
        [LocalizationKeys.Authentication.SecureKeyRecovery.Reset.CONFIRM_SECURE_KEY_PLACEHOLDER] =
            "Confirm New Key",
        [LocalizationKeys.Authentication.SecureKeyRecovery.Reset.CONFIRM_SECURE_KEY_HINT] =
            "Re-enter your new secure key",
        [LocalizationKeys.Authentication.SecureKeyRecovery.Reset.BUTTON] = "Reset Secure Key",
        [LocalizationKeys.Authentication.SignUp.PassPhase.TITLE] = "Set PIN",
        [LocalizationKeys.Authentication.SignUp.PassPhase.DESCRIPTION] = "For quick and secure authentication.",
        [LocalizationKeys.Authentication.SignUp.PassPhase.HINT] = "Your PIN",
        [LocalizationKeys.Authentication.SignUp.PassPhase.WATERMARK] = "••••",
        [LocalizationKeys.Authentication.SignUp.PassPhase.BUTTON] = "Confirm PIN",
        [LocalizationKeys.Authentication.SignIn.TITLE] = "Sign In",
        [LocalizationKeys.Authentication.SignIn.WELCOME] =
            "Welcome back! Let's get you back to your secure, personalized workspace.",
        [LocalizationKeys.Authentication.SignIn.MOBILE_PLACEHOLDER] = "Mobile Number",
        [LocalizationKeys.Authentication.SignIn.MOBILE_HINT] = "Ensure the number is correct",
        [LocalizationKeys.Authentication.SignIn.SECURE_KEY_PLACEHOLDER] = "Secure Key",
        [LocalizationKeys.Authentication.SignIn.SECURE_KEY_HINT] = "Stored only on this device",
        [LocalizationKeys.Authentication.SignIn.ACCOUNT_RECOVERY] = "Forgot key?",
        [LocalizationKeys.Authentication.SignIn.CONTINUE] = "Continue",
        [LocalizationKeys.Authentication.SignIn.RATE_LIMIT_EXCEEDED] = "Sign in attempts exceeded. Please try again later.",
        [LocalizationKeys.MobileVerificationStatus.Error.MOBILE_ALREADY_REGISTERED] =
            "A problem occurred with your registration. If you already have an account, please try logging in or use the account recovery option.",
        [LocalizationKeys.MobileVerificationStatus.AVAILABLE_FOR_REGISTRATION] =
            "This mobile number is available for registration.",
        [LocalizationKeys.MobileVerificationStatus.INCOMPLETE_REGISTRATION_CONTINUE] =
            "Continue your registration with this mobile number.",
        [LocalizationKeys.MobileVerificationStatus.TAKEN_ACTIVE_ACCOUNT] =
            "This mobile number is already registered with an active account. Please sign in instead.",
        [LocalizationKeys.MobileVerificationStatus.TAKEN_INACTIVE_ACCOUNT] =
            "This mobile number is registered but inactive. Please use secure key recovery to regain access.",
        [LocalizationKeys.MobileVerificationStatus.DATA_CORRUPTION_CONTACT_SUPPORT] =
            "There's an issue with your account data. Please contact support for assistance.",
        [LocalizationKeys.MobileVerificationStatus.AVAILABLE_ON_THIS_DEVICE] =
            "This mobile number is available for registration on this device.",
        [LocalizationKeys.MobileVerificationStatus.INCOMPLETE_REGISTRATION_DIFFERENT_DEVICE] =
            "Registration for this number was started on another device. Please continue on the original device or wait for the session to expire.",
        [LocalizationKeys.Verification.Error.INVALID_OTP_CODE] = "Invalid verification code",
        [LocalizationKeys.Registration.Error.FAILED] = "Registration failed",
        [LocalizationKeys.Verification.Error.NO_SESSION] = "Verification session not found",
        [LocalizationKeys.Verification.Error.SESSION_EXPIRED] = "Verification session has expired",
        [LocalizationKeys.Verification.Error.NO_ACTIVE_SESSION] = "No active verification session",
        [LocalizationKeys.Verification.Error.MAX_ATTEMPTS_REACHED] = "Maximum verification attempts reached",
        [LocalizationKeys.Verification.Error.VERIFICATION_FAILED] = "Verification failed",
        [LocalizationKeys.Verification.Error.SESSION_NOT_FOUND] = "Verification session not found",
        [LocalizationKeys.Verification.Error.GLOBAL_RATE_LIMIT_EXCEEDED] =
            "Too many requests. Please try again later",
        [LocalizationKeys.Verification.Redirect.Title.MAX_ATTEMPTS] = "Too Many Attempts",
        [LocalizationKeys.Verification.Redirect.Title.SESSION_EXPIRED] = "Session Expired",
        [LocalizationKeys.Verification.Redirect.Title.SESSION_NOT_FOUND] = "Session Not Found",
        [LocalizationKeys.Verification.Redirect.Title.SERVER_ERROR] = "Connection Error",
        [LocalizationKeys.Verification.Redirect.Title.GENERIC_ERROR] = "Verification Failed",
        [LocalizationKeys.Verification.Redirect.Subtitle.SECURITY_LIMIT] = "Security limit reached",
        [LocalizationKeys.Verification.Redirect.Subtitle.TIMEOUT] = "Verification timeout",
        [LocalizationKeys.Verification.Redirect.Subtitle.INVALID_STATE] = "Invalid session state",
        [LocalizationKeys.Verification.Redirect.Subtitle.TRY_AGAIN] = "Please try again later",
        [LocalizationKeys.Verification.Redirect.Subtitle.RETURNING] = "Returning to start",
        [LocalizationKeys.Verification.Redirect.AUTO_REQUEST_PREFIX] = "Auto-requesting in",
        [LocalizationKeys.Verification.Info.REDIRECTING] = "Redirecting...",
        [LocalizationKeys.Verification.Info.REDIRECTING_IN_SECONDS] = "Redirecting in {0} seconds...",
        [LocalizationKeys.Verification.Info.STEP_OF] = "Step {0} of {1}",
        [LocalizationKeys.ValidationErrors.MobileNumber.MUST_START_WITH_COUNTRY_CODE] = "Must start with +",
        [LocalizationKeys.ValidationErrors.MobileNumber.CONTAINS_NON_DIGITS] = "Digits only after code",
        [LocalizationKeys.ValidationErrors.MobileNumber.INCORRECT_LENGTH] = "{0}-{1} digits required",
        [LocalizationKeys.ValidationErrors.MobileNumber.CANNOT_BE_EMPTY] = "Required field",
        [LocalizationKeys.ResponseErrors.MobileNumber.ACCOUNT_ALREADY_REGISTERED] =
            "Account on this number already registered. Try sign in or use forgot secure key.",
        [LocalizationKeys.ResponseErrors.MobileNumber.UNEXPECTED_MEMBERSHIP_STATUS] =
            "Unexpected membership status. Please try again.",
        [LocalizationKeys.ResponseErrors.General.TIMEOUT_EXCEEDED] = "The operation timed out. Please try again.",
        [LocalizationKeys.ValidationErrors.MobileNumber.REQUIRED] = "Mobile number is required",
        [LocalizationKeys.ValidationErrors.MobileNumberIdentifier.REQUIRED] =
            "Mobile number identifier is required",
        [LocalizationKeys.ValidationErrors.DeviceIdentifier.REQUIRED] = "Device identifier is required",
        [LocalizationKeys.ValidationErrors.SessionIdentifier.REQUIRED] = "Session identifier is required",
        [LocalizationKeys.ValidationErrors.MembershipIdentifier.REQUIRED] = "Membership identifier is required",
        [LocalizationKeys.ValidationErrors.SecureKey.REQUIRED] = "Required field",
        [LocalizationKeys.ValidationErrors.SecureKey.MIN_LENGTH] = "Min {0} characters",
        [LocalizationKeys.ValidationErrors.SecureKey.MAX_LENGTH] = "Max {0} characters",
        [LocalizationKeys.ValidationErrors.SecureKey.NO_SPACES] = "No spaces allowed",
        [LocalizationKeys.ValidationErrors.SecureKey.NO_UPPERCASE] = "Requires an uppercase letter",
        [LocalizationKeys.ValidationErrors.SecureKey.NO_LOWERCASE] = "Requires a lowercase letter",
        [LocalizationKeys.ValidationErrors.SecureKey.NO_DIGIT] = "Requires a digit",
        [LocalizationKeys.ValidationErrors.SecureKey.TOO_SIMPLE] = "Try adding more variety",
        [LocalizationKeys.ValidationErrors.SecureKey.TOO_COMMON] = "Too common",
        [LocalizationKeys.ValidationErrors.SecureKey.SEQUENTIAL_PATTERN] = "No sequences (e.g., abc, 123)",
        [LocalizationKeys.ValidationErrors.SecureKey.REPEATED_CHARS] = "No repeats (e.g., aaa, 111)",
        [LocalizationKeys.ValidationErrors.SecureKey.LACKS_DIVERSITY] = "Requires {0} character types (A, a, 1, $)",
        [LocalizationKeys.ValidationErrors.SecureKey.CONTAINS_APP_NAME] = "Cannot contain app name",
        [LocalizationKeys.ValidationErrors.SecureKey.INVALID_CREDENTIALS] = "Invalid mobile number or password",
        [LocalizationKeys.ValidationErrors.SecureKey.NON_ENGLISH_LETTERS] = "Latin letters only",
        [LocalizationKeys.ValidationErrors.SecureKey.NO_SPECIAL_CHAR] = "Requires a special character",
        [LocalizationKeys.ValidationErrors.VerifySecureKey.DOES_NOT_MATCH] = "Secure keys do not match",
        [LocalizationKeys.ValidationErrors.Strength.INVALID] = "Invalid",
        [LocalizationKeys.ValidationErrors.Strength.VERY_WEAK] = "Very Weak",
        [LocalizationKeys.ValidationErrors.Strength.WEAK] = "Weak",
        [LocalizationKeys.ValidationErrors.Strength.GOOD] = "Good",
        [LocalizationKeys.ValidationErrors.Strength.STRONG] = "Strong",
        [LocalizationKeys.ValidationErrors.Strength.VERY_STRONG] = "Very Strong",
        [LocalizationKeys.ValidationWarnings.SecureKey.NON_LATIN_LETTER] = "Latin letters only",
        [LocalizationKeys.ValidationWarnings.SecureKey.INVALID_CHARACTER] = "Invalid character used",
        [LocalizationKeys.ValidationWarnings.SecureKey.MULTIPLE_CHARACTERS] =
            "Multiple instances of character type",
        [LocalizationKeys.Welcome.SIGN_IN_BUTTON] = "Sign In",
        [LocalizationKeys.Welcome.CREATE_ACCOUNT_BUTTON] = "Create Account",
        [LocalizationKeys.Welcome.Carousel.Slide1.TITLE] = "AI powered safety",
        [LocalizationKeys.Welcome.Carousel.Slide1.DESCRIPTION] = "Your personal AI companion monitors and protects your mental wellbeing",
        [LocalizationKeys.Welcome.Carousel.Slide2.TITLE] = "Mental Protection",
        [LocalizationKeys.Welcome.Carousel.Slide2.DESCRIPTION] = "Real-time content filtering and emotional support when you need it most",
        [LocalizationKeys.Welcome.Carousel.Slide3.TITLE] = "Smart Communities",
        [LocalizationKeys.Welcome.Carousel.Slide3.DESCRIPTION] = "Connect with friends in verified, positive spaces designed for your safety",
        [LocalizationKeys.Welcome.Carousel.Slide4.TITLE] = "Wellness First",
        [LocalizationKeys.Welcome.Carousel.Slide4.DESCRIPTION] = "Track your emotional health with insights and suggestions from our AI",
        [LocalizationKeys.Authentication.WelcomeBack.TITLE] = "Welcome Back!",
        [LocalizationKeys.Authentication.WelcomeBack.DESCRIPTION_OTP_VERIFIED] =
            "You have already verified your mobile number. Let's finish setting up your secure key to protect your account.",
        [LocalizationKeys.Authentication.WelcomeBack.DESCRIPTION_SECURE_KEY_SET] =
            "You have already set your secure key. Let's finish setting up your profile.",
        [LocalizationKeys.Authentication.WelcomeBack.BUTTON_LATER] = "Continue Later",
        [LocalizationKeys.Authentication.WelcomeBack.BUTTON_CONTINUE] = "Continue to Setup",
        [LocalizationKeys.Authentication.WelcomeBack.ERROR_SESSION_MISSING] = "We could not find your session data. Please start the registration process again.",
        [LocalizationKeys.Authentication.WelcomeBack.ERROR_TITLE] = "Session Missing",
        [LocalizationKeys.Authentication.WelcomeBack.ERROR_SUBTITLE] = "Authentication required",
        [LocalizationKeys.Footer.PRIVACY_POLICY] = "Privacy Policy",
        [LocalizationKeys.Footer.TERMS_OF_SERVICE] = "Terms of Service",
        [LocalizationKeys.Footer.SUPPORT] = "Support",
        [LocalizationKeys.Footer.AGREEMENT_TEXT] = "By continuing, you agree to our Terms and Privacy Policy.",
        [LocalizationKeys.Footer.AGREEMENT_PREFIX] = "By continuing, you agree to the ",
        [LocalizationKeys.Footer.AGREEMENT_CONJUNCTION] = " and ",
        [LocalizationKeys.Footer.COPYRIGHT] = "© 2025 Horizon Dynamics. All rights reserved.",
        [LocalizationKeys.Navigation.BACK] = "Back",
        [LocalizationKeys.Navigation.CLOSE] = "Close",
        [LocalizationKeys.Navigation.MINIMIZE] = "Minimize",
        [LocalizationKeys.ProfileMenu.ADD_ACCOUNT] = "Add existing account",
        [LocalizationKeys.ProfileMenu.LOGOUT] = "Ecliptix logout",
        [LocalizationKeys.ProfileMenu.LOGOUT_FROM] = "Log out from",
        [LocalizationKeys.Navigation.MAXIMIZE] = "Maximize",
        [LocalizationKeys.Common.LOADING] = "Loading...",
        [LocalizationKeys.Common.ERROR] = "ERROR",
        [LocalizationKeys.Common.SUCCESS] = "Success",
        [LocalizationKeys.Common.CANCEL] = "Cancel",
        [LocalizationKeys.Common.UNEXPECTED_ERROR] = "An unexpected error occurred",
        [LocalizationKeys.Common.OK] = "OK",
        [LocalizationKeys.Common.NO_INTERNET_CONNECTION] = "No internet connection",
        [LocalizationKeys.Common.CHECK_CONNECTION] = "No internet connection. Please check your network",
        [LocalizationKeys.NetworkNotification.NoInternet.TITLE] = "No Internet Connection",
        [LocalizationKeys.NetworkNotification.NoInternet.DESCRIPTION] = "No Internet Connection. Check your connection and try again",
        [LocalizationKeys.NetworkNotification.CheckingInternet.TITLE] = "Checking Connection",
        [LocalizationKeys.NetworkNotification.CheckingInternet.DESCRIPTION] = "Verifying internet connectivity",
        [LocalizationKeys.NetworkNotification.InternetRestored.TITLE] = "Connection Restored",
        [LocalizationKeys.NetworkNotification.InternetRestored.DESCRIPTION] = "Connection restored. You're back online!",
        [LocalizationKeys.NetworkNotification.Connecting.TITLE] = "Connecting",
        [LocalizationKeys.NetworkNotification.Connecting.DESCRIPTION] = "Establishing connection to server",
        [LocalizationKeys.NetworkNotification.Reconnecting.TITLE] = "Reconnecting",
        [LocalizationKeys.NetworkNotification.Reconnecting.DESCRIPTION] = "Attempting to reconnect to server",
        [LocalizationKeys.NetworkNotification.ServerNotResponding.TITLE] = "Server Error",
        [LocalizationKeys.NetworkNotification.ServerNotResponding.DESCRIPTION] = "Server not responding. Please try again later.",
        [LocalizationKeys.NetworkNotification.ServerShuttingDown.TITLE] = "Server Maintenance",
        [LocalizationKeys.NetworkNotification.ServerShuttingDown.DESCRIPTION] = "Server is shutting down",
        [LocalizationKeys.NetworkNotification.RetriesExhausted.TITLE] = "Connection Failed",
        [LocalizationKeys.NetworkNotification.RetriesExhausted.DESCRIPTION] =
            "Unable to connect after multiple attempts",
        [LocalizationKeys.NetworkNotification.ServerReconnected.TITLE] = "Reconnected",
        [LocalizationKeys.NetworkNotification.ServerReconnected.DESCRIPTION] = "Successfully reconnected to server",
        [LocalizationKeys.NetworkNotification.Button.RETRY] = "Retry",
        [LocalizationKeys.LanguageDetection.TITLE] = "Language Suggestion",
        [LocalizationKeys.LanguageDetection.PROMPT] = "Switch to {0}?",
        [LocalizationKeys.LanguageDetection.BUTTON_CONFIRM] = "Switch",
        [LocalizationKeys.LanguageDetection.BUTTON_DECLINE] = "Not Now",
        [LocalizationKeys.EcliptixProtectionProtocol.TITLE] = "Ecliptix Protection Protocol",
        [LocalizationKeys.EcliptixProtectionProtocol.TEXT] = "Protected by EPP",
        [LocalizationKeys.EcliptixProtectionProtocol.FEATURE_END_TO_END_ENCRYPTION] = "End-to-end encrypted communications",
        [LocalizationKeys.EcliptixProtectionProtocol.FEATURE_FORWARD_SECRECY] = "Perfect forward secrecy for all messages",
        [LocalizationKeys.EcliptixProtectionProtocol.FEATURE_OPAQUE_PROTOCOL] = "Passwords and PIN never leave device",
        [LocalizationKeys.NetworkStatus.ONLINE] = "Online",
        [LocalizationKeys.NetworkStatus.OFFLINE] = "Offline",
        [LocalizationKeys.NetworkStatus.SERVER_ERROR] = "Server Error",
        [LocalizationKeys.LanguagePicker.TITLE] = "Supported languages",
        [LocalizationKeys.LanguagePicker.SUBTITLE] = "Choose your preferred language",
        [LocalizationKeys.Authentication.SignUp.CompleteProfile.TITLE] = "Complete Your Profile",
        [LocalizationKeys.Authentication.SignUp.CompleteProfile.DESCRIPTION] = "Help your friends find and recognize you. You can always update this later.",
        [LocalizationKeys.Authentication.SignUp.CompleteProfile.DISPLAY_NAME_WATERMARK] = "Display name",
        [LocalizationKeys.Authentication.SignUp.CompleteProfile.DISPLAY_NAME_HINT] = "How others will see you (e.g. Alex)",
        [LocalizationKeys.Authentication.SignUp.CompleteProfile.PROFILE_NAME_WATERMARK] = "Profile name",
        [LocalizationKeys.Authentication.SignUp.CompleteProfile.PROFILE_NAME_HINT] = "Unique ID (e.g. alexsmith)",
        [LocalizationKeys.Authentication.SignUp.CompleteProfile.DATE_OF_BIRTH_WATERMARK] = "mm/dd/yyyy",
        [LocalizationKeys.Authentication.SignUp.CompleteProfile.DATE_OF_BIRTH_HINT] = "Must be 13-17 years old",
        [LocalizationKeys.Authentication.SignUp.CompleteProfile.BUTTON_COMPLETE] = "Complete Setup",
        [LocalizationKeys.ValidationErrors.Profile.REQUIRED] = "Profile name is required",
        [LocalizationKeys.ValidationErrors.Profile.REQUIRED_DISPLAY_NAME] = "Display name is required",
        [LocalizationKeys.ValidationErrors.Profile.INVALID_LENGTH] = "Must be between {0} and {1} characters",
        [LocalizationKeys.ValidationErrors.Profile.INVALID_CHARACTERS] = "Only Latin letters, numbers, '_', '.', '-' allowed",
        [LocalizationKeys.ValidationErrors.Profile.INVALID_START_END] = "Cannot start or end with '_', '.', '-'",
        [LocalizationKeys.ValidationErrors.Profile.CONSECUTIVE_SEPARATORS] = "Cannot have consecutive symbols (e.g. '..', '__')",
        [LocalizationKeys.ValidationErrors.Profile.RESERVED_WORD] = "This profile name is reserved",
        [LocalizationKeys.ValidationErrors.Profile.DISPLAY_NAME_TOO_LONG] = "Max {0} characters allowed",
        [LocalizationKeys.ValidationErrors.Profile.INVALID_DISPLAY_CHARS] = "Contains invalid characters",
        [LocalizationKeys.ValidationErrors.Profile.NO_DOUBLE_SPACES] = "Cannot contain double spaces",
        [LocalizationKeys.CountryPicker.TITLE] = "Country Code",
        [LocalizationKeys.CountryPicker.SUBTITLE] = "Select country for phone number",
        [LocalizationKeys.Countires.US] = "United States",
        [LocalizationKeys.Countires.UA] = "Ukraine",
    }.ToFrozenDictionary();

    private static readonly FrozenDictionary<string, string> UkrainianStrings = new Dictionary<string, string>
    {
        [ErrorI18NKeys.VALIDATION] = "Перевірка не пройшла; перевірте дані та повторіть спробу.",
        [ErrorI18NKeys.MAX_ATTEMPTS] =
            "Досягнуто максимальну кількість спроб. Зачекайте або зверніться до підтримки.",
        [ErrorI18NKeys.INVALID_MOBILE] = "Неправильний формат номера телефону.",
        [ErrorI18NKeys.OTP_EXPIRED] = "Термін дії коду підтвердження минув. Запитайте новий.",
        [ErrorI18NKeys.NOT_FOUND] = "Запитаний ресурс не знайдено.",
        [ErrorI18NKeys.ALREADY_EXISTS] = "Такий ресурс уже існує.",
        [ErrorI18NKeys.UNAUTHENTICATED] = "Потрібна автентифікація. Увійдіть ще раз.",
        [ErrorI18NKeys.PERMISSION_DENIED] = "У вас немає дозволу на цю дію.",
        [ErrorI18NKeys.PRECONDITION_FAILED] = "Дію неможливо виконати в поточному стані.",
        [ErrorI18NKeys.CONFLICT] = "Операція конфліктує з наявними даними. Оновіть та повторіть.",
        [ErrorI18NKeys.RESOURCE_EXHAUSTED] = "Забагато спроб. Спробуйте пізніше.",
        [ErrorI18NKeys.SERVICE_UNAVAILABLE] = "Сервіс тимчасово недоступний. Спробуйте пізніше.",
        [ErrorI18NKeys.DEPENDENCY_UNAVAILABLE] = "Зовнішня залежність недоступна. Повторіть спробу.",
        [ErrorI18NKeys.DEADLINE_EXCEEDED] = "Час очікування запиту вичерпано. Спробуйте ще раз.",
        [ErrorI18NKeys.CANCELLED] = "Запит було скасовано.",
        [ErrorI18NKeys.INTERNAL] = "Сталася помилка. Спробуйте пізніше.",
        [ErrorI18NKeys.DATABASE_UNAVAILABLE] = "База даних недоступна. Повторіть спробу пізніше.",
        [LocalizationKeys.Common.SERVER_UNAVAILABLE] = "Сервер наразі недоступний. Будь ласка, спробуйте пізніше.",
        [LocalizationKeys.Authentication.Error.NAVIGATION_FAILURE] = "Не вдалося перейти до головного вікна",
        [LocalizationKeys.Authentication.Error.MEMBERSHIP_IDENTIFIER_REQUIRED] =
            "Ідентифікатор учасника є обов'язковим",
        [LocalizationKeys.Authentication.Error.SESSION_EXPIRED] =
            "Ваша сесія закінчилася. Будь ласка, почніть реєстрацію спочатку.",
        [LocalizationKeys.Authentication.Error.REGISTRATION_INCOMPLETE] =
            "Дані реєстрації неповні. Будь ласка, почніть процес реєстрації знову.",
        [LocalizationKeys.Authentication.SignUp.SignUpMobileVerification.TITLE] = "Створити акаунт",
        [LocalizationKeys.Authentication.SignUp.SignUpMobileVerification.DESCRIPTION] =
            "Давайте почнемо з перевірки вашого номера мобільного телефону. Ми надішлемо вам безпечний код підтвердження.",
        [LocalizationKeys.Authentication.SignUp.SignUpMobileVerification.HINT] = "Будь ласка, переконайтеся, що номер правильний",
        [LocalizationKeys.Authentication.SignUp.SignUpMobileVerification.WATERMARK] = "Номер мобільного",
        [LocalizationKeys.Authentication.SignUp.SignUpMobileVerification.BUTTON] = "Продовжити",
        [LocalizationKeys.Authentication.SecureKeyRecovery.RecoveryMobileVerification.TITLE] = "Скинути ключ безпеки",
        [LocalizationKeys.Authentication.SecureKeyRecovery.RecoveryMobileVerification.DESCRIPTION] =
            "Підтвердьте номер для отримання коду підтвердження.",
        [LocalizationKeys.Authentication.SecureKeyRecovery.RecoveryMobileVerification.HINT] = "Будь ласка, переконайтеся, що номер правильний.",
        [LocalizationKeys.Authentication.SecureKeyRecovery.RecoveryMobileVerification.WATERMARK] = "Номер мобільного",
        [LocalizationKeys.Authentication.SecureKeyRecovery.RecoveryMobileVerification.BUTTON] = "Продовжити",
        [LocalizationKeys.Authentication.SignUp.VerificationCodeEntry.TITLE] = "Підтвердження номера",
        [LocalizationKeys.Authentication.SignUp.VerificationCodeEntry.DESCRIPTION] =
            "Ми надіслали 6-значний код на {0}. Введіть його нижче, щоб підтвердити ваш номер.",
        [LocalizationKeys.Authentication.SignUp.VerificationCodeEntry.HINT] = "Код підтвердження",
        [LocalizationKeys.Authentication.SignUp.VerificationCodeEntry.ERROR_INVALID_CODE] =
            "Неправильний код. Спробуйте ще раз.",
        [LocalizationKeys.Authentication.SignUp.VerificationCodeEntry.BUTTON_VERIFY] = "Підтвердити",
        [LocalizationKeys.Authentication.SignUp.VerificationCodeEntry.BUTTON_RESEND] = "Надіслати знову",
        [LocalizationKeys.Authentication.SignUp.VerificationCodeEntry.NOT_RECEIVED] = "Не отримали код?",
        [LocalizationKeys.Authentication.SignUp.NicknameInput.TITLE] = "Оберіть нікнейм",
        [LocalizationKeys.Authentication.SignUp.NicknameInput.DESCRIPTION] = "Це ім'я буде видимим для інших.",
        [LocalizationKeys.Authentication.SignUp.NicknameInput.HINT] = "Ваш нікнейм",
        [LocalizationKeys.Authentication.SignUp.NicknameInput.WATERMARK] = "Нікнейм",
        [LocalizationKeys.Authentication.SignUp.NicknameInput.BUTTON] = "Підтвердити",
        [LocalizationKeys.Authentication.SignUp.SecureKeyConfirmation.TITLE] = "Встановіть ключ безпеки",
        [LocalizationKeys.Authentication.SignUp.SecureKeyConfirmation.DESCRIPTION] =
            "Оберіть надійний ключ безпеки для доступу до облікового запису. Він зберігається лише на вашому пристрої.",
        [LocalizationKeys.Authentication.SignUp.SecureKeyConfirmation.SECURE_KEY_PLACEHOLDER] = "Ключ безпеки",
        [LocalizationKeys.Authentication.SignUp.SecureKeyConfirmation.SECURE_KEY_HINT] =
            "Мін 6 символів: велика, мала літера, цифра",
        [LocalizationKeys.Authentication.SignUp.SecureKeyConfirmation.VERIFY_SECURE_KEY_PLACEHOLDER] =
            "Повторіть ключ",
        [LocalizationKeys.Authentication.SignUp.SecureKeyConfirmation.VERIFY_SECURE_KEY_HINT] =
            "Введіть ключ ще раз для підтвердження",
        [LocalizationKeys.Authentication.SignUp.SecureKeyConfirmation.ERROR_SECURE_KEY_MISMATCH] =
            "Ключі безпеки не збігаються.",
        [LocalizationKeys.Authentication.SignUp.SecureKeyConfirmation.BUTTON] = "Продовжити",
        [LocalizationKeys.Authentication.SignUp.SecureKeyConfirmation.REQUIREMENTS_SUCCESS_TITLE] = "Усі мінімальні вимоги виконано",
        [LocalizationKeys.Authentication.SignUp.SecureKeyConfirmation.REQUIREMENTS_TITLE] = "Вимоги безпеки:",
        [LocalizationKeys.Authentication.SecureKeyRecovery.Reset.TITLE] = "Скидання ключа безпеки",
        [LocalizationKeys.Authentication.SecureKeyRecovery.Reset.DESCRIPTION] =
            "Створіть новий ключ безпеки для облікового запису.",
        [LocalizationKeys.Authentication.SecureKeyRecovery.Reset.NEW_SECURE_KEY_PLACEHOLDER] = "Новий ключ безпеки",
        [LocalizationKeys.Authentication.SecureKeyRecovery.Reset.NEW_SECURE_KEY_HINT] =
            "Мін 6 символів: велика, мала літера, цифра",
        [LocalizationKeys.Authentication.SecureKeyRecovery.Reset.CONFIRM_SECURE_KEY_PLACEHOLDER] =
            "Підтвердіть новий ключ",
        [LocalizationKeys.Authentication.SecureKeyRecovery.Reset.CONFIRM_SECURE_KEY_HINT] =
            "Введіть новий ключ ще раз",
        [LocalizationKeys.Authentication.SecureKeyRecovery.Reset.BUTTON] = "Скинути ключ безпеки",
        [LocalizationKeys.Authentication.SignUp.PassPhase.TITLE] = "Встановіть PIN-код",
        [LocalizationKeys.Authentication.SignUp.PassPhase.DESCRIPTION] = "Для швидкої та безпечної автентифікації.",
        [LocalizationKeys.Authentication.SignUp.PassPhase.HINT] = "Ваш PIN-код",
        [LocalizationKeys.Authentication.SignUp.PassPhase.WATERMARK] = "••••",
        [LocalizationKeys.Authentication.SignUp.PassPhase.BUTTON] = "Підтвердити PIN",
        [LocalizationKeys.Authentication.SignIn.TITLE] = "Вхід",
        [LocalizationKeys.Authentication.SignIn.WELCOME] = "З поверненням! Увійдіть у свій захищений простір.",
        [LocalizationKeys.Authentication.SignIn.MOBILE_PLACEHOLDER] = "Номер телефону",
        [LocalizationKeys.Authentication.SignIn.MOBILE_HINT] = "Переконайтеся, що номер правильний",
        [LocalizationKeys.Authentication.SignIn.SECURE_KEY_PLACEHOLDER] = "Ключ безпеки",
        [LocalizationKeys.Authentication.SignIn.SECURE_KEY_HINT] = "Зберігається лише на цьому пристрої",
        [LocalizationKeys.Authentication.SignIn.ACCOUNT_RECOVERY] = "Забули ключ?",
        [LocalizationKeys.Authentication.SignIn.CONTINUE] = "Продовжити",
        [LocalizationKeys.Authentication.SignIn.RATE_LIMIT_EXCEEDED] = "Перевищено кількість спроб входу. Спробуйте пізніше.",
        [LocalizationKeys.MobileVerificationStatus.Error.MOBILE_ALREADY_REGISTERED] =
            "Під час реєстрації сталася помилка. Якщо у вас вже є акаунт, будь ласка, спробуйте увійти або скористайтеся опцією відновлення доступу.",
        [LocalizationKeys.MobileVerificationStatus.AVAILABLE_FOR_REGISTRATION] = "Цей номер доступний для реєстрації.",
        [LocalizationKeys.MobileVerificationStatus.INCOMPLETE_REGISTRATION_CONTINUE] =
            "Продовжіть реєстрацію з цим номером.",
        [LocalizationKeys.MobileVerificationStatus.TAKEN_ACTIVE_ACCOUNT] =
            "Цей номер вже зареєстровано з активним акаунтом. Будь ласка, увійдіть.",
        [LocalizationKeys.MobileVerificationStatus.TAKEN_INACTIVE_ACCOUNT] =
            "Цей номер зареєстровано, але акаунт неактивний. Скористайтеся відновленням ключа безпеки.",
        [LocalizationKeys.MobileVerificationStatus.DATA_CORRUPTION_CONTACT_SUPPORT] =
            "Виникла проблема з даними вашого акаунта. Будь ласка, зверніться до підтримки.",
        [LocalizationKeys.MobileVerificationStatus.AVAILABLE_ON_THIS_DEVICE] =
            "Цей номер доступний для реєстрації на цьому пристрої.",
        [LocalizationKeys.MobileVerificationStatus.INCOMPLETE_REGISTRATION_DIFFERENT_DEVICE] =
            "Реєстрацію для цього номера було розпочато на іншому пристрої. Будь ласка, продовжте на початковому пристрої або зачекайте, поки сесія завершиться.",
        [LocalizationKeys.Verification.Error.INVALID_OTP_CODE] = "Неправильний код підтвердження",
        [LocalizationKeys.Registration.Error.FAILED] = "Не вдалося зареєструватися",
        [LocalizationKeys.Verification.Error.NO_SESSION] = "Сесія підтвердження не знайдена",
        [LocalizationKeys.Verification.Error.SESSION_EXPIRED] = "Термін дії сесії підтвердження минув",
        [LocalizationKeys.Verification.Error.NO_ACTIVE_SESSION] = "Немає активної сесії підтвердження",
        [LocalizationKeys.Verification.Error.MAX_ATTEMPTS_REACHED] =
            "Досягнуто максимальну кількість спроб підтвердження",
        [LocalizationKeys.Verification.Error.VERIFICATION_FAILED] = "Підтвердження не вдалося",
        [LocalizationKeys.Verification.Error.SESSION_NOT_FOUND] = "Сесія підтвердження не знайдена",
        [LocalizationKeys.Verification.Error.GLOBAL_RATE_LIMIT_EXCEEDED] =
            "Занадто багато запитів. Спробуйте пізніше",
        [LocalizationKeys.Verification.Redirect.Title.MAX_ATTEMPTS] = "Забагато спроб",
        [LocalizationKeys.Verification.Redirect.Title.SESSION_EXPIRED] = "Сесія закінчилася",
        [LocalizationKeys.Verification.Redirect.Title.SESSION_NOT_FOUND] = "Сесію не знайдено",
        [LocalizationKeys.Verification.Redirect.Title.SERVER_ERROR] = "Помилка з'єднання",
        [LocalizationKeys.Verification.Redirect.Title.GENERIC_ERROR] = "Помилка перевірки",
        [LocalizationKeys.Verification.Redirect.Subtitle.SECURITY_LIMIT] = "Ліміт безпеки вичерпано",
        [LocalizationKeys.Verification.Redirect.Subtitle.TIMEOUT] = "Час вийшов",
        [LocalizationKeys.Verification.Redirect.Subtitle.INVALID_STATE] = "Недійсний стан сесії",
        [LocalizationKeys.Verification.Redirect.Subtitle.TRY_AGAIN] = "Спробуйте пізніше",
        [LocalizationKeys.Verification.Redirect.Subtitle.RETURNING] = "Повернення на початок",
        [LocalizationKeys.Verification.Redirect.AUTO_REQUEST_PREFIX] = "Автоматичний запит через",
        [LocalizationKeys.Verification.Info.REDIRECTING] = "Перенаправлення...",
        [LocalizationKeys.Verification.Info.REDIRECTING_IN_SECONDS] = "Перенаправлення через {0} секунд...",
        [LocalizationKeys.Verification.Info.STEP_OF] = "Крок {0} з {1}",
        [LocalizationKeys.ValidationErrors.MobileNumber.MUST_START_WITH_COUNTRY_CODE] = "Має починатись із +",
        [LocalizationKeys.ValidationErrors.MobileNumber.CONTAINS_NON_DIGITS] = "Лише цифри після коду",
        [LocalizationKeys.ValidationErrors.MobileNumber.INCORRECT_LENGTH] = "Потрібно {0}-{1} цифр",
        [LocalizationKeys.ValidationErrors.MobileNumber.CANNOT_BE_EMPTY] = "Обов'язкове поле",
        [LocalizationKeys.ValidationErrors.MobileNumber.REQUIRED] = "Номер мобільного телефону є обов'язковим",
        [LocalizationKeys.ValidationErrors.MobileNumberIdentifier.REQUIRED] =
            "Ідентифікатор номера мобільного телефону є обов'язковим",
        [LocalizationKeys.ValidationErrors.DeviceIdentifier.REQUIRED] = "Ідентифікатор пристрою є обов'язковим",
        [LocalizationKeys.ValidationErrors.SessionIdentifier.REQUIRED] = "Ідентифікатор сесії є обов'язковим",
        [LocalizationKeys.ValidationErrors.MembershipIdentifier.REQUIRED] = "Ідентифікатор учасника є обов'язковим",
        [LocalizationKeys.ResponseErrors.MobileNumber.ACCOUNT_ALREADY_REGISTERED] =
            "Акаунт з цим номером вже зареєстровано. Спробуйте увійти або скористайтеся відновленням пароля.",
        [LocalizationKeys.ResponseErrors.MobileNumber.UNEXPECTED_MEMBERSHIP_STATUS] =
            "Неочікуваний статус системи. Спробуйте ще раз.",
        [LocalizationKeys.ResponseErrors.General.TIMEOUT_EXCEEDED] =
            "Операція перевищила час очікування. Спробуйте ще раз.",
        [LocalizationKeys.ValidationErrors.SecureKey.REQUIRED] = "Обов'язкове поле",
        [LocalizationKeys.ValidationErrors.SecureKey.MIN_LENGTH] = "Мін. {0} символів",
        [LocalizationKeys.ValidationErrors.SecureKey.MAX_LENGTH] = "Макс. {0} символів",
        [LocalizationKeys.ValidationErrors.SecureKey.NO_SPACES] = "Без пробілів",
        [LocalizationKeys.ValidationErrors.SecureKey.NO_UPPERCASE] = "Потрібна велика літера",
        [LocalizationKeys.ValidationErrors.SecureKey.NO_LOWERCASE] = "Потрібна мала літера",
        [LocalizationKeys.ValidationErrors.SecureKey.NO_DIGIT] = "Потрібна цифра",
        [LocalizationKeys.ValidationErrors.SecureKey.TOO_SIMPLE] = "Додайте більше різноманітності",
        [LocalizationKeys.ValidationErrors.SecureKey.TOO_COMMON] = "Занадто поширений",
        [LocalizationKeys.ValidationErrors.SecureKey.SEQUENTIAL_PATTERN] = "Без послідовностей (abc, 123)",
        [LocalizationKeys.ValidationErrors.SecureKey.REPEATED_CHARS] = "Без повторів (aaa, 111)",
        [LocalizationKeys.ValidationErrors.SecureKey.LACKS_DIVERSITY] = "Потрібно {0} типи символів (A, a, 1, $)",
        [LocalizationKeys.ValidationErrors.SecureKey.CONTAINS_APP_NAME] = "Не може містити назву додатку",
        [LocalizationKeys.ValidationErrors.SecureKey.INVALID_CREDENTIALS] = "Неправильний номер телефону або пароль",
        [LocalizationKeys.ValidationErrors.SecureKey.NON_ENGLISH_LETTERS] = "Лише латинські літери",
        [LocalizationKeys.ValidationErrors.SecureKey.NO_SPECIAL_CHAR] = "Потрібен спеціальний символ",
        [LocalizationKeys.ValidationErrors.VerifySecureKey.DOES_NOT_MATCH] = "Ключі безпеки не збігаються",
        [LocalizationKeys.ValidationErrors.Strength.INVALID] = "Некоректний",
        [LocalizationKeys.ValidationErrors.Strength.VERY_WEAK] = "Дуже слабкий",
        [LocalizationKeys.ValidationErrors.Strength.WEAK] = "Слабкий",
        [LocalizationKeys.ValidationErrors.Strength.GOOD] = "Хороший",
        [LocalizationKeys.ValidationErrors.Strength.STRONG] = "Сильний",
        [LocalizationKeys.ValidationErrors.Strength.VERY_STRONG] = "Дуже сильний",
        [LocalizationKeys.ValidationWarnings.SecureKey.NON_LATIN_LETTER] = "Лише латинські літери",
        [LocalizationKeys.ValidationWarnings.SecureKey.INVALID_CHARACTER] = "Використано недопустимий символ",
        [LocalizationKeys.ValidationWarnings.SecureKey.MULTIPLE_CHARACTERS] = "Кілька символів одного типу",
        [LocalizationKeys.Welcome.SIGN_IN_BUTTON] = "Увійти",
        [LocalizationKeys.Welcome.CREATE_ACCOUNT_BUTTON] = "Створити акаунт",
        [LocalizationKeys.Welcome.Carousel.Slide1.TITLE] = "Безпека на основі ШІ",
        [LocalizationKeys.Welcome.Carousel.Slide1.DESCRIPTION] = "Ваш особистий AI-компаньйон стежить і захищає ваше психічне здоров'я",
        [LocalizationKeys.Welcome.Carousel.Slide2.TITLE] = "Психічний захист",
        [LocalizationKeys.Welcome.Carousel.Slide2.DESCRIPTION] = "Фільтрація контенту в реальному часі та емоційна підтримка коли вона вам найбільше потрібна",
        [LocalizationKeys.Welcome.Carousel.Slide3.TITLE] = "Розумні спільноти",
        [LocalizationKeys.Welcome.Carousel.Slide3.DESCRIPTION] = "Зв'яжіться з друзями у перевірених позитивних просторах створених для вашої безпеки",
        [LocalizationKeys.Welcome.Carousel.Slide4.TITLE] = "Здоров'я понад усе",
        [LocalizationKeys.Welcome.Carousel.Slide4.DESCRIPTION] = "Відстежуйте своє емоційне здоров'я з insights та пропозиціями від нашого AI",
        [LocalizationKeys.Authentication.WelcomeBack.TITLE] = "З поверненням!",
        [LocalizationKeys.Authentication.WelcomeBack.DESCRIPTION_OTP_VERIFIED] =
            "Ви вже підтвердили номер телефону. Тепер налаштуйте ключ безпеки для захисту вашого акаунту.",
        [LocalizationKeys.Authentication.WelcomeBack.DESCRIPTION_SECURE_KEY_SET] =
            "Ви вже встановили ключ безпеки. Завершіть налаштування профілю",
        [LocalizationKeys.Authentication.WelcomeBack.BUTTON_LATER] = "Продовжити пізніше",
        [LocalizationKeys.Authentication.WelcomeBack.BUTTON_CONTINUE] = "Продовжити",
        [LocalizationKeys.Authentication.WelcomeBack.ERROR_SESSION_MISSING] = "Не вдалося знайти дані вашої сесії. Будь ласка, розпочніть процес реєстрації заново.",
        [LocalizationKeys.Authentication.WelcomeBack.ERROR_TITLE] = "Сесія відсутня",
        [LocalizationKeys.Authentication.WelcomeBack.ERROR_SUBTITLE] = "Потрібна автентифікація",
        [LocalizationKeys.Footer.PRIVACY_POLICY] = "Політикою конфіденційності",
        [LocalizationKeys.Footer.TERMS_OF_SERVICE] = "Умовами надання послуг",
        [LocalizationKeys.Footer.SUPPORT] = "Підтримка",
        [LocalizationKeys.Footer.AGREEMENT_TEXT] =
            "Продовжуючи, ви погоджуєтесь з нашими Умовами та Політикою конфіденційності.",
        [LocalizationKeys.Footer.AGREEMENT_PREFIX] = "Продовжуючи, ви погоджуєтесь з ",
        [LocalizationKeys.Footer.AGREEMENT_CONJUNCTION] = " та ",
        [LocalizationKeys.Footer.COPYRIGHT] = "© 2025 Horizon Dynamics. Усі права захищено.",
        [LocalizationKeys.Navigation.BACK] = "Назад",
        [LocalizationKeys.Navigation.CLOSE] = "Закрити",
        [LocalizationKeys.Navigation.MINIMIZE] = "Згорнути",
        [LocalizationKeys.ProfileMenu.ADD_ACCOUNT] = "Додати існуючий обліковий запис",
        [LocalizationKeys.ProfileMenu.LOGOUT] = "Вихід з Ecliptix",
        [LocalizationKeys.ProfileMenu.LOGOUT_FROM] = "Вийти з",
        [LocalizationKeys.Navigation.MAXIMIZE] = "Розгорнути",
        [LocalizationKeys.Common.LOADING] = "Завантаження...",
        [LocalizationKeys.Common.ERROR] = "Помилка",
        [LocalizationKeys.Common.SUCCESS] = "Успішно",
        [LocalizationKeys.Common.CANCEL] = "Скасувати",
        [LocalizationKeys.Common.UNEXPECTED_ERROR] = "Несподівана помилка",
        [LocalizationKeys.Common.OK] = "Гаразд",
        [LocalizationKeys.Common.NO_INTERNET_CONNECTION] = "Немає підключення до інтернету",
        [LocalizationKeys.Common.CHECK_CONNECTION] = "Немає підключення до інтернету. Будь ласка, перевірте підключення до мережі",
        [LocalizationKeys.NetworkNotification.NoInternet.TITLE] = "Немає підключення до інтернету",
        [LocalizationKeys.NetworkNotification.NoInternet.DESCRIPTION] = "Немає підключення до інтернету. Будь ласка, перевірте підключення до мережі",
        [LocalizationKeys.NetworkNotification.CheckingInternet.TITLE] = "Перевірка з'єднання",
        [LocalizationKeys.NetworkNotification.CheckingInternet.DESCRIPTION] =
            "Перевіряємо підключення до інтернету",
        [LocalizationKeys.NetworkNotification.InternetRestored.TITLE] = "З'єднання відновлено",
        [LocalizationKeys.NetworkNotification.InternetRestored.DESCRIPTION] = "Підключення до інтернету відновлено.  Ви знову онлайн!",
        [LocalizationKeys.NetworkNotification.Connecting.TITLE] = "Підключення",
        [LocalizationKeys.NetworkNotification.Connecting.DESCRIPTION] = "Встановлюємо з'єднання з сервером",
        [LocalizationKeys.NetworkNotification.Reconnecting.TITLE] = "Перепідключення",
        [LocalizationKeys.NetworkNotification.Reconnecting.DESCRIPTION] =
            "Намагаємось відновити з'єднання з сервером",
        [LocalizationKeys.NetworkNotification.ServerNotResponding.TITLE] = "Помилка сервера",
        [LocalizationKeys.NetworkNotification.ServerNotResponding.DESCRIPTION] = "Сервер не відповідає. Будь ласка, спробуйте пізніше",
        [LocalizationKeys.NetworkNotification.ServerShuttingDown.TITLE] = "Обслуговування сервера",
        [LocalizationKeys.NetworkNotification.ServerShuttingDown.DESCRIPTION] = "Сервер вимикається",
        [LocalizationKeys.NetworkNotification.RetriesExhausted.TITLE] = "Не вдалось підключитись",
        [LocalizationKeys.NetworkNotification.RetriesExhausted.DESCRIPTION] =
            "Неможливо підключитись після кількох спроб",
        [LocalizationKeys.NetworkNotification.ServerReconnected.TITLE] = "Підключено",
        [LocalizationKeys.NetworkNotification.ServerReconnected.DESCRIPTION] = "Успішно підключено до сервера",
        [LocalizationKeys.NetworkNotification.Button.RETRY] = "Повторити",
        [LocalizationKeys.LanguageDetection.TITLE] = "Пропозиція мови",
        [LocalizationKeys.LanguageDetection.PROMPT] = "Перемкнутись на {0}?",
        [LocalizationKeys.LanguageDetection.BUTTON_CONFIRM] = "Змінити",
        [LocalizationKeys.LanguageDetection.BUTTON_DECLINE] = "Не зараз",
        [LocalizationKeys.EcliptixProtectionProtocol.TITLE] = "Протокол захисту Ecliptix",
        [LocalizationKeys.EcliptixProtectionProtocol.TEXT] = "Захищено EPP",
        [LocalizationKeys.EcliptixProtectionProtocol.FEATURE_END_TO_END_ENCRYPTION] = "Наскрізне шифрування комунікацій",
        [LocalizationKeys.EcliptixProtectionProtocol.FEATURE_FORWARD_SECRECY] = "Досконала пряма секретність для всіх повідомлень",
        [LocalizationKeys.EcliptixProtectionProtocol.FEATURE_OPAQUE_PROTOCOL] = "Паролі та PIN ніколи не залишають пристрій",
        [LocalizationKeys.NetworkStatus.ONLINE] = "Онлайн",
        [LocalizationKeys.NetworkStatus.OFFLINE] = "Офлайн",
        [LocalizationKeys.NetworkStatus.SERVER_ERROR] = "Помилка сервера",
        [LocalizationKeys.LanguagePicker.TITLE] = "Підтримувані мови",
        [LocalizationKeys.LanguagePicker.SUBTITLE] = "Виберіть бажану мову",
        [LocalizationKeys.Authentication.SignUp.CompleteProfile.TITLE] = "Заповніть профіль",
        [LocalizationKeys.Authentication.SignUp.CompleteProfile.DESCRIPTION] = "Допоможіть друзям знайти та впізнати вас. Ви зможете змінити це пізніше.",
        [LocalizationKeys.Authentication.SignUp.CompleteProfile.DISPLAY_NAME_WATERMARK] = "Відображуване імʼя",
        [LocalizationKeys.Authentication.SignUp.CompleteProfile.DISPLAY_NAME_HINT] = "Як вас бачитимуть інші (напр. Олексій)",
        [LocalizationKeys.Authentication.SignUp.CompleteProfile.PROFILE_NAME_WATERMARK] = "Імʼя профілю",
        [LocalizationKeys.Authentication.SignUp.CompleteProfile.PROFILE_NAME_HINT] = "Унікальний ID (напр. oleksii)",
        [LocalizationKeys.Authentication.SignUp.CompleteProfile.DATE_OF_BIRTH_WATERMARK] = "дд.мм.рррр",
        [LocalizationKeys.Authentication.SignUp.CompleteProfile.DATE_OF_BIRTH_HINT] = "Вам має бути 13-17 років",
        [LocalizationKeys.Authentication.SignUp.CompleteProfile.BUTTON_COMPLETE] = "Завершити налаштування",
        [LocalizationKeys.ValidationErrors.Profile.REQUIRED] = "Ім'я профілю є обов'язковим",
        [LocalizationKeys.ValidationErrors.Profile.REQUIRED_DISPLAY_NAME] = "Відображуване ім'я є обов'язковим",
        [LocalizationKeys.ValidationErrors.Profile.INVALID_LENGTH] = "Має бути від {0} до {1} символів",
        [LocalizationKeys.ValidationErrors.Profile.INVALID_CHARACTERS] = "Лише латинські літери, цифри, '_', '.', '-'",
        [LocalizationKeys.ValidationErrors.Profile.INVALID_START_END] = "Не може починатися або закінчуватися на '_', '.', '-'",
        [LocalizationKeys.ValidationErrors.Profile.CONSECUTIVE_SEPARATORS] = "Не можна використовувати символи підряд (напр. '..', '__')",
        [LocalizationKeys.ValidationErrors.Profile.RESERVED_WORD] = "Це ім'я профілю зарезервовано",
        [LocalizationKeys.ValidationErrors.Profile.DISPLAY_NAME_TOO_LONG] = "Максимум {0} символів",
        [LocalizationKeys.ValidationErrors.Profile.INVALID_DISPLAY_CHARS] = "Містить недопустимі символи",
        [LocalizationKeys.ValidationErrors.Profile.NO_DOUBLE_SPACES] = "Подвійні пробіли заборонені",
        [LocalizationKeys.CountryPicker.TITLE] = "Код країни",
        [LocalizationKeys.CountryPicker.SUBTITLE] = "Оберіть країну для номера телефону",
        [LocalizationKeys.Countires.US] = "Сполучені Штати",
        [LocalizationKeys.Countires.UA] = "Україна",
    }.ToFrozenDictionary();

    public static readonly FrozenDictionary<string, FrozenDictionary<string, string>> AllLanguages =
        new Dictionary<string, FrozenDictionary<string, string>>
        {
            ["en-US"] = EnglishStrings,
            ["uk-UA"] = UkrainianStrings
        }.ToFrozenDictionary();
}
