syntax = "proto3";

package ecliptix.transport.device_provisioning;
option csharp_namespace = "Ecliptix.Protobuf.Transport.DeviceProvisioning";

enum DeviceProvisioningEventType {
  DEVICE_PROVISIONING_EVENT_TYPE_UNSPECIFIED = 0;
  DEVICE_PROVISIONING_REGISTER_DEVICE = 1;
  DEVICE_PROVISIONING_SECURE_CHANNEL_ESTABLISH = 2;
  DEVICE_PROVISIONING_SECURE_CHANNEL_RESTORE = 3;
  DEVICE_PROVISIONING_SECURE_CHANNEL_AUTH_ESTABLISH = 4;
  DEVICE_PROVISIONING_GET_SERVER_PUBLIC_KEYS = 5;
}

message AppDevice {
  bytes app_instance_id = 1;
  bytes device_id = 2;

  enum DeviceType {
    DEVICE_TYPE_UNSPECIFIED = 0;
    DESKTOP = 1;
    MOBILE = 2;
  }

  DeviceType device_type = 3;
}

message DeviceRegistrationResponse {
  enum Status {
    STATUS_UNSPECIFIED = 0;
    NEW_REGISTRATION = 1;
    ALREADY_EXISTS = 2;
    INVALID_REQUEST = 3;
    INTERNAL_ERROR = 4;
  }

  Status status = 1;
  string message = 2;
}

message RestoreChannelRequest {}

message RestoreChannelResponse {
  enum Status {
    STATUS_UNSPECIFIED = 0;
    SESSION_NOT_FOUND = 1;
    SESSION_RESTORED = 2;
  }

  Status status = 1;
  uint32 sending_chain_length = 2;
  uint32 receiving_chain_length = 3;
}

message AuthenticatedEstablishRequest {
  bytes membership_unique_id = 1;
  bytes account_unique_id = 2;
  bytes master_key_fingerprint = 3;
  bytes client_pub_key_exchange = 4;
}

message GetServerPublicKeysRequest {}

message GetServerPublicKeysResponse {
  bytes server_public_key = 1;
  bytes server_kyber_public_key = 2;
}
