namespace Ecliptix.Utilities.Failures.Network;

public enum NetworkFailureType
{
    DATA_CENTER_NOT_RESPONDING,
    DATA_CENTER_SHUTDOWN,
    INVALID_REQUEST_TYPE,
    ECLIPTIX_PROTOCOL_FAILURE,
    RSA_ENCRYPTION_FAILURE,
    PROTOCOL_STATE_MISMATCH,
    OPERATION_CANCELLED,
    CRITICAL_AUTHENTICATION_FAILURE,
    CONNECTION_FAILED
}
