namespace Ecliptix.Utilities.Failures.Membership;

public enum LogoutFailureType
{
    NETWORK_REQUEST_FAILED,
    ALREADY_LOGGED_OUT,
    SESSION_NOT_FOUND,
    INVALID_MEMBERSHIP_IDENTIFIER,
    CRYPTOGRAPHIC_OPERATION_FAILED,
    INVALID_REVOCATION_PROOF,
    UNEXPECTED_ERROR
}
