<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <PlatformTarget Condition="$([MSBuild]::IsOSPlatform('Windows'))">x64</PlatformTarget>
        <PlatformTarget Condition="$([MSBuild]::IsOSPlatform('OSX'))">arm64</PlatformTarget>
        <PlatformTarget Condition="$([MSBuild]::IsOSPlatform('Linux'))">x64</PlatformTarget>
        <LangVersion>14</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="../Ecliptix.Utilities/Ecliptix.Utilities.csproj" />
        <ProjectReference Include="../Ecliptix.Protected.Protocol/Ecliptix.Protected.Protocol.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="Native/macos/libsslpinning.dylib" Condition="Exists('Native/macos/libsslpinning.dylib')">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <Link>libsslpinning.dylib</Link>
        </Content>
        <Content Include="native/windows/ecliptix.client.dll" Condition="Exists('native/windows/ecliptix.client.dll')">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <Link>ecliptix.client.dll</Link>
        </Content>
        <Content Include="libcrypto-3-x64.dll" Condition="('$(RuntimeIdentifier)' == 'win-x64' OR ('$(RuntimeIdentifier)' == '' AND $([MSBuild]::IsOSPlatform('Windows')))) AND Exists('ecliptix.client.dll')">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <TargetPath>libcrypto-3-x64.dll</TargetPath>
        </Content>
        <Content Include="native/linux/libecliptix.client.so" Condition="Exists('native/linux/libecliptix.client.so')">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <Link>libecliptix.client.so</Link>
        </Content>
        <None Remove="libcrypto-3-x64.dll" />
        <Content Include="libcrypto-3-x64.dll">
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>

    </ItemGroup>
    <ItemGroup>
      <PackageReference Include="Avalonia" Version="11.3.10" />
      <PackageReference Include="Avalonia.Desktop" Version="11.3.10" />
      <PackageReference Include="Avalonia.Diagnostics" Version="11.3.10" />
      <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.10" />
      <PackageReference Include="Avalonia.Themes.Simple" Version="11.3.10" />
    </ItemGroup>

</Project>