namespace Ecliptix.Core.Controls.Common;

public enum DetailedConnectivityStatus
{
    NO_INTERNET_CONNECTION,
    CHECKING_INTERNET_CONNECTION,
    INTERNET_RESTORED,
    CONNECTING_TO_SERVER,
    RECONNECTING,
    SERVER_NOT_RESPONDING,
    SERVER_SHUTTING_DOWN,
    RETRIES_EXHAUSTED,
    SERVER_RECONNECTED
}
