<Project>
    <PropertyGroup>
        <Nullable>enable</Nullable>
        <NuGetAudit>false</NuGetAudit>
        <AvaloniaVersion>11.3.2</AvaloniaVersion>

        <MajorVersion>0</MajorVersion>
        <MinorVersion>5684</MinorVersion>
        <PatchVersion>2295</PatchVersion>
        <BuildNumber Condition="'$(BuildNumber)' == ''">0</BuildNumber>

        <AssemblyVersion>$(MajorVersion).$(MinorVersion).$(PatchVersion).0</AssemblyVersion>
        <FileVersion>$(MajorVersion).$(MinorVersion).$(PatchVersion).$(BuildNumber)</FileVersion>
        <Version>$(MajorVersion).$(MinorVersion).$(PatchVersion)</Version>
        <AssemblyInformationalVersion>$(Version)-build.$(BuildNumber)</AssemblyInformationalVersion>

        <Product>Ecliptix Desktop</Product>
        <Company>Ecliptix</Company>
        <Copyright>Copyright © Ecliptix $(Year)</Copyright>
        <UsedAvaloniaProducts>Ecliptix Desktop</UsedAvaloniaProducts>
        <Description>Cross-platform desktop application for secure communication and data management</Description>

        <Year>$([System.DateTime]::Now.Year)</Year>
        <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)' == 'Release'">
        <DebugType>none</DebugType>
        <DebugSymbols>false</DebugSymbols>
    </PropertyGroup>
</Project>
