namespace Ecliptix.Utilities.Failures.EcliptixProtocol;

public enum EcliptixProtocolFailureType
{
    GENERIC,
    DECODE_FAILED,
    DERIVE_KEY_FAILED,
    HANDSHAKE_FAILED,
    PEER_PUB_KEY_FAILED,
    INVALID_INPUT,
    OBJECT_DISPOSED,
    ALLOCATION_FAILED,
    PINNING_FAILURE,
    BUFFER_TOO_SMALL,
    DATA_TOO_LARGE,
    KEY_GENERATION_FAILED,
    PREPARE_LOCAL_FAILED,
    MEMORY_BUFFER_ERROR,
    STATE_MISMATCH,
}
