namespace Ecliptix.Utilities.Failures.Authentication;

public enum AuthenticationFailureType
{
    INVALID_CREDENTIALS,
    LOGIN_ATTEMPT_EXCEEDED,
    MOBILE_NUMBER_REQUIRED,
    SECURE_KEY_REQUIRED,
    UNEXPECTED_ERROR,
    SECURE_MEMORY_ALLOCATION_FAILED,
    SECURE_MEMORY_WRITE_FAILED,
    KEY_DERIVATION_FAILED,
    MASTER_KEY_DERIVATION_FAILED,
    NETWORK_REQUEST_FAILED,
    INVALID_MEMBERSHIP_IDENTIFIER,
    IDENTITY_STORAGE_FAILED,
    CRITICAL_AUTHENTICATION_ERROR,
    KEYCHAIN_CORRUPTED
}
