namespace Ecliptix.Utilities.Failures.CertificatePinning;

public enum CertificatePinningFailureType
{
    SERVICE_NOT_INITIALIZED,
    SERVICE_DISPOSED,
    LIBRARY_INITIALIZATION_FAILED,
    INITIALIZATION_EXCEPTION,
    CERTIFICATE_DATA_REQUIRED,
    HOSTNAME_REQUIRED,
    CERTIFICATE_VALIDATION_FAILED,
    CERTIFICATE_VALIDATION_EXCEPTION,
    PLAINTEXT_REQUIRED,
    RSA_ENCRYPTION_FAILED,
    RSA_ENCRYPTION_EXCEPTION,
    CIPHERTEXT_REQUIRED,
    RSA_DECRYPTION_FAILED,
    RSA_DECRYPTION_EXCEPTION,
    MESSAGE_REQUIRED,
    INVALID_SIGNATURE_SIZE,
    ED_25519_VERIFICATION_ERROR,
    ED_25519_VERIFICATION_EXCEPTION,
    SERVICE_INITIALIZING,
    SERVICE_INVALID_STATE
}
