<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <LangVersion>14</LangVersion>
    </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ecliptix.Utilities\Ecliptix.Utilities.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Ecliptix.OPAQUE.Client" Version="1.0.0-ci.16" />
  </ItemGroup>

</Project>
