<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>14</LangVersion>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Avalonia" Version="11.3.10" />
      <PackageReference Include="Avalonia.Desktop" Version="11.3.10" />
      <PackageReference Include="Avalonia.Diagnostics" Version="11.3.10" />
      <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.10" />
      <PackageReference Include="Avalonia.Themes.Simple" Version="11.3.10" />
      <PackageReference Include="Google.Protobuf" Version="3.33.2" />
      <PackageReference Include="Grpc.Core.Api" Version="2.76.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Ecliptix.Protobufs\Ecliptix.Protobufs.csproj" />
    </ItemGroup>

</Project>
